// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApplicationEnumsProto.proto

package org.onosproject.grpc.models;

public final class ApplicationEnumsProto {
  private ApplicationEnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.ApplicationStateProto}
   */
  public enum ApplicationStateProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Indicates that application has been installed, but is not running.
     * </pre>
     *
     * <code>INSTALLED = 0;</code>
     */
    INSTALLED(0),
    /**
     * <pre>
     * Indicates that application is active.
     * </pre>
     *
     * <code>ACTIVE = 1;</code>
     */
    ACTIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Indicates that application has been installed, but is not running.
     * </pre>
     *
     * <code>INSTALLED = 0;</code>
     */
    public static final int INSTALLED_VALUE = 0;
    /**
     * <pre>
     * Indicates that application is active.
     * </pre>
     *
     * <code>ACTIVE = 1;</code>
     */
    public static final int ACTIVE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationStateProto valueOf(int value) {
      return forNumber(value);
    }

    public static ApplicationStateProto forNumber(int value) {
      switch (value) {
        case 0: return INSTALLED;
        case 1: return ACTIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationStateProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationStateProto> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationStateProto>() {
            public ApplicationStateProto findValueByNumber(int number) {
              return ApplicationStateProto.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.onosproject.grpc.models.ApplicationEnumsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ApplicationStateProto[] VALUES = values();

    public static ApplicationStateProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationStateProto(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ApplicationStateProto)
  }

  /**
   * Protobuf enum {@code proto.ApplicationRoleProto}
   */
  public enum ApplicationRoleProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Indicates that an application has an ADMIN role.
     * </pre>
     *
     * <code>ADMIN = 0;</code>
     */
    ADMIN(0),
    /**
     * <pre>
     * Indicates that an application has a USER role.
     * </pre>
     *
     * <code>USER = 1;</code>
     */
    USER(1),
    /**
     * <pre>
     * Indicates that an application role has not been specified.
     * </pre>
     *
     * <code>UNSPECIFIED = 2;</code>
     */
    UNSPECIFIED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Indicates that an application has an ADMIN role.
     * </pre>
     *
     * <code>ADMIN = 0;</code>
     */
    public static final int ADMIN_VALUE = 0;
    /**
     * <pre>
     * Indicates that an application has a USER role.
     * </pre>
     *
     * <code>USER = 1;</code>
     */
    public static final int USER_VALUE = 1;
    /**
     * <pre>
     * Indicates that an application role has not been specified.
     * </pre>
     *
     * <code>UNSPECIFIED = 2;</code>
     */
    public static final int UNSPECIFIED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationRoleProto valueOf(int value) {
      return forNumber(value);
    }

    public static ApplicationRoleProto forNumber(int value) {
      switch (value) {
        case 0: return ADMIN;
        case 1: return USER;
        case 2: return UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationRoleProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationRoleProto> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationRoleProto>() {
            public ApplicationRoleProto findValueByNumber(int number) {
              return ApplicationRoleProto.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.onosproject.grpc.models.ApplicationEnumsProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final ApplicationRoleProto[] VALUES = values();

    public static ApplicationRoleProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationRoleProto(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ApplicationRoleProto)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ApplicationEnumsProto.proto\022\005proto*2\n\025" +
      "ApplicationStateProto\022\r\n\tINSTALLED\020\000\022\n\n\006" +
      "ACTIVE\020\001*<\n\024ApplicationRoleProto\022\t\n\005ADMI" +
      "N\020\000\022\010\n\004USER\020\001\022\017\n\013UNSPECIFIED\020\002B\035\n\033org.on" +
      "osproject.grpc.modelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
