// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BandEnumsProto.proto

package org.onosproject.grpc.models;

public final class BandEnumsProto {
  private BandEnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * Specifies the type of band.
   * </pre>
   *
   * Protobuf enum {@code proto.BandTypeProto}
   */
  public enum BandTypeProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     **
     * Simple rate limiter which drops packets
     * when the rate is exceeded.
     * </pre>
     *
     * <code>DROP = 0;</code>
     */
    DROP(0),
    /**
     * <pre>
     **
     * defines a simple DiffServ policer that remark
     * the drop precedence of the DSCP field in the
     * IP header of the packets that exceed the band
     * rate value.
     * </pre>
     *
     * <code>REMARK = 1;</code>
     */
    REMARK(1),
    /**
     * <pre>
     **
     * defines an experimental meter band.
     * </pre>
     *
     * <code>EXPERIMENTAL = 2;</code>
     */
    EXPERIMENTAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     **
     * Simple rate limiter which drops packets
     * when the rate is exceeded.
     * </pre>
     *
     * <code>DROP = 0;</code>
     */
    public static final int DROP_VALUE = 0;
    /**
     * <pre>
     **
     * defines a simple DiffServ policer that remark
     * the drop precedence of the DSCP field in the
     * IP header of the packets that exceed the band
     * rate value.
     * </pre>
     *
     * <code>REMARK = 1;</code>
     */
    public static final int REMARK_VALUE = 1;
    /**
     * <pre>
     **
     * defines an experimental meter band.
     * </pre>
     *
     * <code>EXPERIMENTAL = 2;</code>
     */
    public static final int EXPERIMENTAL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BandTypeProto valueOf(int value) {
      return forNumber(value);
    }

    public static BandTypeProto forNumber(int value) {
      switch (value) {
        case 0: return DROP;
        case 1: return REMARK;
        case 2: return EXPERIMENTAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BandTypeProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BandTypeProto> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BandTypeProto>() {
            public BandTypeProto findValueByNumber(int number) {
              return BandTypeProto.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.onosproject.grpc.models.BandEnumsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final BandTypeProto[] VALUES = values();

    public static BandTypeProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BandTypeProto(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.BandTypeProto)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BandEnumsProto.proto\022\005proto*7\n\rBandTyp" +
      "eProto\022\010\n\004DROP\020\000\022\n\n\006REMARK\020\001\022\020\n\014EXPERIME" +
      "NTAL\020\002B\035\n\033org.onosproject.grpc.modelsb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
