// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FlowRuleEnumsProto.proto

package org.onosproject.grpc.models;

public final class FlowRuleEnumsProto {
  private FlowRuleEnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Corresponds to org.onosproject.net.flow.FlowRule enums.
   * </pre>
   *
   * Protobuf enum {@code proto.FlowRemoveReasonProto}
   */
  public enum FlowRemoveReasonProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IDLE_TIMEOUT = 0;</code>
     */
    IDLE_TIMEOUT(0),
    /**
     * <code>HARD_TIMEOUT = 1;</code>
     */
    HARD_TIMEOUT(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2),
    /**
     * <code>GROUP_DELETE = 3;</code>
     */
    GROUP_DELETE(3),
    /**
     * <code>METER_DELETE = 4;</code>
     */
    METER_DELETE(4),
    /**
     * <code>EVICTION = 5;</code>
     */
    EVICTION(5),
    /**
     * <code>NO_REASON = 6;</code>
     */
    NO_REASON(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IDLE_TIMEOUT = 0;</code>
     */
    public static final int IDLE_TIMEOUT_VALUE = 0;
    /**
     * <code>HARD_TIMEOUT = 1;</code>
     */
    public static final int HARD_TIMEOUT_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;
    /**
     * <code>GROUP_DELETE = 3;</code>
     */
    public static final int GROUP_DELETE_VALUE = 3;
    /**
     * <code>METER_DELETE = 4;</code>
     */
    public static final int METER_DELETE_VALUE = 4;
    /**
     * <code>EVICTION = 5;</code>
     */
    public static final int EVICTION_VALUE = 5;
    /**
     * <code>NO_REASON = 6;</code>
     */
    public static final int NO_REASON_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FlowRemoveReasonProto valueOf(int value) {
      return forNumber(value);
    }

    public static FlowRemoveReasonProto forNumber(int value) {
      switch (value) {
        case 0: return IDLE_TIMEOUT;
        case 1: return HARD_TIMEOUT;
        case 2: return DELETE;
        case 3: return GROUP_DELETE;
        case 4: return METER_DELETE;
        case 5: return EVICTION;
        case 6: return NO_REASON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FlowRemoveReasonProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FlowRemoveReasonProto> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FlowRemoveReasonProto>() {
            public FlowRemoveReasonProto findValueByNumber(int number) {
              return FlowRemoveReasonProto.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.onosproject.grpc.models.FlowRuleEnumsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final FlowRemoveReasonProto[] VALUES = values();

    public static FlowRemoveReasonProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FlowRemoveReasonProto(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.FlowRemoveReasonProto)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030FlowRuleEnumsProto.proto\022\005proto*\210\001\n\025Fl" +
      "owRemoveReasonProto\022\020\n\014IDLE_TIMEOUT\020\000\022\020\n" +
      "\014HARD_TIMEOUT\020\001\022\n\n\006DELETE\020\002\022\020\n\014GROUP_DEL" +
      "ETE\020\003\022\020\n\014METER_DELETE\020\004\022\014\n\010EVICTION\020\005\022\r\n" +
      "\tNO_REASON\020\006B\035\n\033org.onosproject.grpc.mod" +
      "elsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
