// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FlowRuleProto.proto

package org.onosproject.grpc.models;

/**
 * <pre>
 * Corresponds to org.onosproject.net.flow.DefaultFlowRule.
 * </pre>
 *
 * Protobuf type {@code proto.FlowRuleProto}
 */
public  final class FlowRuleProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.FlowRuleProto)
    FlowRuleProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlowRuleProto.newBuilder() to construct.
  private FlowRuleProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlowRuleProto() {
    priority_ = 0;
    appId_ = 0;
    deviceId_ = "";
    flowId_ = 0L;
    timeout_ = 0;
    permanent_ = false;
    tableId_ = 0;
    tableName_ = "";
    reason_ = 0;
    appName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlowRuleProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            priority_ = input.readInt32();
            break;
          }
          case 16: {

            appId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 32: {

            flowId_ = input.readInt64();
            break;
          }
          case 40: {

            timeout_ = input.readInt32();
            break;
          }
          case 48: {

            permanent_ = input.readBool();
            break;
          }
          case 56: {

            tableId_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 74: {
            org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder subBuilder = null;
            if (selector_ != null) {
              subBuilder = selector_.toBuilder();
            }
            selector_ = input.readMessage(org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(selector_);
              selector_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder subBuilder = null;
            if (treatment_ != null) {
              subBuilder = treatment_.toBuilder();
            }
            treatment_ = input.readMessage(org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(treatment_);
              treatment_ = subBuilder.buildPartial();
            }

            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            reason_ = rawValue;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.onosproject.grpc.models.FlowRuleProtoOuterClass.internal_static_proto_FlowRuleProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.onosproject.grpc.models.FlowRuleProtoOuterClass.internal_static_proto_FlowRuleProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.onosproject.grpc.models.FlowRuleProto.class, org.onosproject.grpc.models.FlowRuleProto.Builder.class);
  }

  public static final int PRIORITY_FIELD_NUMBER = 1;
  private int priority_;
  /**
   * <code>int32 priority = 1;</code>
   */
  public int getPriority() {
    return priority_;
  }

  public static final int APP_ID_FIELD_NUMBER = 2;
  private int appId_;
  /**
   * <code>int32 app_id = 2;</code>
   */
  public int getAppId() {
    return appId_;
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>string device_id = 3;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string device_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOW_ID_FIELD_NUMBER = 4;
  private long flowId_;
  /**
   * <code>int64 flow_id = 4;</code>
   */
  public long getFlowId() {
    return flowId_;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 5;
  private int timeout_;
  /**
   * <code>int32 timeout = 5;</code>
   */
  public int getTimeout() {
    return timeout_;
  }

  public static final int PERMANENT_FIELD_NUMBER = 6;
  private boolean permanent_;
  /**
   * <code>bool permanent = 6;</code>
   */
  public boolean getPermanent() {
    return permanent_;
  }

  public static final int TABLE_ID_FIELD_NUMBER = 7;
  private int tableId_;
  /**
   * <code>int32 table_id = 7;</code>
   */
  public int getTableId() {
    return tableId_;
  }

  public static final int TABLE_NAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string table_name = 8;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string table_name = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELECTOR_FIELD_NUMBER = 9;
  private org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto selector_;
  /**
   * <code>.proto.TrafficSelectorProto selector = 9;</code>
   */
  public boolean hasSelector() {
    return selector_ != null;
  }
  /**
   * <code>.proto.TrafficSelectorProto selector = 9;</code>
   */
  public org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto getSelector() {
    return selector_ == null ? org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.getDefaultInstance() : selector_;
  }
  /**
   * <code>.proto.TrafficSelectorProto selector = 9;</code>
   */
  public org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProtoOrBuilder getSelectorOrBuilder() {
    return getSelector();
  }

  public static final int TREATMENT_FIELD_NUMBER = 10;
  private org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto treatment_;
  /**
   * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
   */
  public boolean hasTreatment() {
    return treatment_ != null;
  }
  /**
   * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
   */
  public org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto getTreatment() {
    return treatment_ == null ? org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.getDefaultInstance() : treatment_;
  }
  /**
   * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
   */
  public org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProtoOrBuilder getTreatmentOrBuilder() {
    return getTreatment();
  }

  public static final int REASON_FIELD_NUMBER = 11;
  private int reason_;
  /**
   * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
   */
  public int getReasonValue() {
    return reason_;
  }
  /**
   * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
   */
  public org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto getReason() {
    @SuppressWarnings("deprecation")
    org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto result = org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.valueOf(reason_);
    return result == null ? org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.UNRECOGNIZED : result;
  }

  public static final int APP_NAME_FIELD_NUMBER = 12;
  private volatile java.lang.Object appName_;
  /**
   * <code>string app_name = 12;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <code>string app_name = 12;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (priority_ != 0) {
      output.writeInt32(1, priority_);
    }
    if (appId_ != 0) {
      output.writeInt32(2, appId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceId_);
    }
    if (flowId_ != 0L) {
      output.writeInt64(4, flowId_);
    }
    if (timeout_ != 0) {
      output.writeInt32(5, timeout_);
    }
    if (permanent_ != false) {
      output.writeBool(6, permanent_);
    }
    if (tableId_ != 0) {
      output.writeInt32(7, tableId_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tableName_);
    }
    if (selector_ != null) {
      output.writeMessage(9, getSelector());
    }
    if (treatment_ != null) {
      output.writeMessage(10, getTreatment());
    }
    if (reason_ != org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.IDLE_TIMEOUT.getNumber()) {
      output.writeEnum(11, reason_);
    }
    if (!getAppNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, appName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, priority_);
    }
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, appId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceId_);
    }
    if (flowId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, flowId_);
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, timeout_);
    }
    if (permanent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, permanent_);
    }
    if (tableId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, tableId_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tableName_);
    }
    if (selector_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getSelector());
    }
    if (treatment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getTreatment());
    }
    if (reason_ != org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.IDLE_TIMEOUT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, reason_);
    }
    if (!getAppNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, appName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.onosproject.grpc.models.FlowRuleProto)) {
      return super.equals(obj);
    }
    org.onosproject.grpc.models.FlowRuleProto other = (org.onosproject.grpc.models.FlowRuleProto) obj;

    boolean result = true;
    result = result && (getPriority()
        == other.getPriority());
    result = result && (getAppId()
        == other.getAppId());
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    result = result && (getFlowId()
        == other.getFlowId());
    result = result && (getTimeout()
        == other.getTimeout());
    result = result && (getPermanent()
        == other.getPermanent());
    result = result && (getTableId()
        == other.getTableId());
    result = result && getTableName()
        .equals(other.getTableName());
    result = result && (hasSelector() == other.hasSelector());
    if (hasSelector()) {
      result = result && getSelector()
          .equals(other.getSelector());
    }
    result = result && (hasTreatment() == other.hasTreatment());
    if (hasTreatment()) {
      result = result && getTreatment()
          .equals(other.getTreatment());
    }
    result = result && reason_ == other.reason_;
    result = result && getAppName()
        .equals(other.getAppName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + FLOW_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFlowId());
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (37 * hash) + PERMANENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPermanent());
    hash = (37 * hash) + TABLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTableId();
    hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    if (hasSelector()) {
      hash = (37 * hash) + SELECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getSelector().hashCode();
    }
    if (hasTreatment()) {
      hash = (37 * hash) + TREATMENT_FIELD_NUMBER;
      hash = (53 * hash) + getTreatment().hashCode();
    }
    hash = (37 * hash) + REASON_FIELD_NUMBER;
    hash = (53 * hash) + reason_;
    hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.onosproject.grpc.models.FlowRuleProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.onosproject.grpc.models.FlowRuleProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Corresponds to org.onosproject.net.flow.DefaultFlowRule.
   * </pre>
   *
   * Protobuf type {@code proto.FlowRuleProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.FlowRuleProto)
      org.onosproject.grpc.models.FlowRuleProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.FlowRuleProtoOuterClass.internal_static_proto_FlowRuleProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.FlowRuleProtoOuterClass.internal_static_proto_FlowRuleProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.FlowRuleProto.class, org.onosproject.grpc.models.FlowRuleProto.Builder.class);
    }

    // Construct using org.onosproject.grpc.models.FlowRuleProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      priority_ = 0;

      appId_ = 0;

      deviceId_ = "";

      flowId_ = 0L;

      timeout_ = 0;

      permanent_ = false;

      tableId_ = 0;

      tableName_ = "";

      if (selectorBuilder_ == null) {
        selector_ = null;
      } else {
        selector_ = null;
        selectorBuilder_ = null;
      }
      if (treatmentBuilder_ == null) {
        treatment_ = null;
      } else {
        treatment_ = null;
        treatmentBuilder_ = null;
      }
      reason_ = 0;

      appName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.onosproject.grpc.models.FlowRuleProtoOuterClass.internal_static_proto_FlowRuleProto_descriptor;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.FlowRuleProto getDefaultInstanceForType() {
      return org.onosproject.grpc.models.FlowRuleProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.onosproject.grpc.models.FlowRuleProto build() {
      org.onosproject.grpc.models.FlowRuleProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.FlowRuleProto buildPartial() {
      org.onosproject.grpc.models.FlowRuleProto result = new org.onosproject.grpc.models.FlowRuleProto(this);
      result.priority_ = priority_;
      result.appId_ = appId_;
      result.deviceId_ = deviceId_;
      result.flowId_ = flowId_;
      result.timeout_ = timeout_;
      result.permanent_ = permanent_;
      result.tableId_ = tableId_;
      result.tableName_ = tableName_;
      if (selectorBuilder_ == null) {
        result.selector_ = selector_;
      } else {
        result.selector_ = selectorBuilder_.build();
      }
      if (treatmentBuilder_ == null) {
        result.treatment_ = treatment_;
      } else {
        result.treatment_ = treatmentBuilder_.build();
      }
      result.reason_ = reason_;
      result.appName_ = appName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.onosproject.grpc.models.FlowRuleProto) {
        return mergeFrom((org.onosproject.grpc.models.FlowRuleProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.onosproject.grpc.models.FlowRuleProto other) {
      if (other == org.onosproject.grpc.models.FlowRuleProto.getDefaultInstance()) return this;
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (other.getFlowId() != 0L) {
        setFlowId(other.getFlowId());
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      if (other.getPermanent() != false) {
        setPermanent(other.getPermanent());
      }
      if (other.getTableId() != 0) {
        setTableId(other.getTableId());
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (other.hasSelector()) {
        mergeSelector(other.getSelector());
      }
      if (other.hasTreatment()) {
        mergeTreatment(other.getTreatment());
      }
      if (other.reason_ != 0) {
        setReasonValue(other.getReasonValue());
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.onosproject.grpc.models.FlowRuleProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.onosproject.grpc.models.FlowRuleProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int priority_ ;
    /**
     * <code>int32 priority = 1;</code>
     */
    public int getPriority() {
      return priority_;
    }
    /**
     * <code>int32 priority = 1;</code>
     */
    public Builder setPriority(int value) {
      
      priority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 priority = 1;</code>
     */
    public Builder clearPriority() {
      
      priority_ = 0;
      onChanged();
      return this;
    }

    private int appId_ ;
    /**
     * <code>int32 app_id = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }
    /**
     * <code>int32 app_id = 2;</code>
     */
    public Builder setAppId(int value) {
      
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 app_id = 2;</code>
     */
    public Builder clearAppId() {
      
      appId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string device_id = 3;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_id = 3;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 3;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 3;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private long flowId_ ;
    /**
     * <code>int64 flow_id = 4;</code>
     */
    public long getFlowId() {
      return flowId_;
    }
    /**
     * <code>int64 flow_id = 4;</code>
     */
    public Builder setFlowId(long value) {
      
      flowId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 flow_id = 4;</code>
     */
    public Builder clearFlowId() {
      
      flowId_ = 0L;
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <code>int32 timeout = 5;</code>
     */
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <code>int32 timeout = 5;</code>
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeout = 5;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }

    private boolean permanent_ ;
    /**
     * <code>bool permanent = 6;</code>
     */
    public boolean getPermanent() {
      return permanent_;
    }
    /**
     * <code>bool permanent = 6;</code>
     */
    public Builder setPermanent(boolean value) {
      
      permanent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool permanent = 6;</code>
     */
    public Builder clearPermanent() {
      
      permanent_ = false;
      onChanged();
      return this;
    }

    private int tableId_ ;
    /**
     * <code>int32 table_id = 7;</code>
     */
    public int getTableId() {
      return tableId_;
    }
    /**
     * <code>int32 table_id = 7;</code>
     */
    public Builder setTableId(int value) {
      
      tableId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 table_id = 7;</code>
     */
    public Builder clearTableId() {
      
      tableId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <code>string table_name = 8;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table_name = 8;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 8;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 8;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto selector_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProtoOrBuilder> selectorBuilder_;
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public boolean hasSelector() {
      return selectorBuilder_ != null || selector_ != null;
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto getSelector() {
      if (selectorBuilder_ == null) {
        return selector_ == null ? org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.getDefaultInstance() : selector_;
      } else {
        return selectorBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public Builder setSelector(org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto value) {
      if (selectorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        selector_ = value;
        onChanged();
      } else {
        selectorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public Builder setSelector(
        org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder builderForValue) {
      if (selectorBuilder_ == null) {
        selector_ = builderForValue.build();
        onChanged();
      } else {
        selectorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public Builder mergeSelector(org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto value) {
      if (selectorBuilder_ == null) {
        if (selector_ != null) {
          selector_ =
            org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.newBuilder(selector_).mergeFrom(value).buildPartial();
        } else {
          selector_ = value;
        }
        onChanged();
      } else {
        selectorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public Builder clearSelector() {
      if (selectorBuilder_ == null) {
        selector_ = null;
        onChanged();
      } else {
        selector_ = null;
        selectorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder getSelectorBuilder() {
      
      onChanged();
      return getSelectorFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    public org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProtoOrBuilder getSelectorOrBuilder() {
      if (selectorBuilder_ != null) {
        return selectorBuilder_.getMessageOrBuilder();
      } else {
        return selector_ == null ?
            org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.getDefaultInstance() : selector_;
      }
    }
    /**
     * <code>.proto.TrafficSelectorProto selector = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProtoOrBuilder> 
        getSelectorFieldBuilder() {
      if (selectorBuilder_ == null) {
        selectorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProto.Builder, org.onosproject.grpc.models.TrafficSelectorProtoOuterClass.TrafficSelectorProtoOrBuilder>(
                getSelector(),
                getParentForChildren(),
                isClean());
        selector_ = null;
      }
      return selectorBuilder_;
    }

    private org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto treatment_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProtoOrBuilder> treatmentBuilder_;
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public boolean hasTreatment() {
      return treatmentBuilder_ != null || treatment_ != null;
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto getTreatment() {
      if (treatmentBuilder_ == null) {
        return treatment_ == null ? org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.getDefaultInstance() : treatment_;
      } else {
        return treatmentBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public Builder setTreatment(org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto value) {
      if (treatmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        treatment_ = value;
        onChanged();
      } else {
        treatmentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public Builder setTreatment(
        org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder builderForValue) {
      if (treatmentBuilder_ == null) {
        treatment_ = builderForValue.build();
        onChanged();
      } else {
        treatmentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public Builder mergeTreatment(org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto value) {
      if (treatmentBuilder_ == null) {
        if (treatment_ != null) {
          treatment_ =
            org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.newBuilder(treatment_).mergeFrom(value).buildPartial();
        } else {
          treatment_ = value;
        }
        onChanged();
      } else {
        treatmentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public Builder clearTreatment() {
      if (treatmentBuilder_ == null) {
        treatment_ = null;
        onChanged();
      } else {
        treatment_ = null;
        treatmentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder getTreatmentBuilder() {
      
      onChanged();
      return getTreatmentFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    public org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProtoOrBuilder getTreatmentOrBuilder() {
      if (treatmentBuilder_ != null) {
        return treatmentBuilder_.getMessageOrBuilder();
      } else {
        return treatment_ == null ?
            org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.getDefaultInstance() : treatment_;
      }
    }
    /**
     * <code>.proto.TrafficTreatmentProto treatment = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProtoOrBuilder> 
        getTreatmentFieldBuilder() {
      if (treatmentBuilder_ == null) {
        treatmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProto.Builder, org.onosproject.grpc.models.TrafficTreatmentProtoOuterClass.TrafficTreatmentProtoOrBuilder>(
                getTreatment(),
                getParentForChildren(),
                isClean());
        treatment_ = null;
      }
      return treatmentBuilder_;
    }

    private int reason_ = 0;
    /**
     * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
     */
    public int getReasonValue() {
      return reason_;
    }
    /**
     * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
     */
    public Builder setReasonValue(int value) {
      reason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
     */
    public org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto getReason() {
      @SuppressWarnings("deprecation")
      org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto result = org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.valueOf(reason_);
      return result == null ? org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
     */
    public Builder setReason(org.onosproject.grpc.models.FlowRuleEnumsProto.FlowRemoveReasonProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      reason_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.FlowRemoveReasonProto reason = 11;</code>
     */
    public Builder clearReason() {
      
      reason_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <code>string app_name = 12;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_name = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_name = 12;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app_name = 12;</code>
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <code>string app_name = 12;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.FlowRuleProto)
  }

  // @@protoc_insertion_point(class_scope:proto.FlowRuleProto)
  private static final org.onosproject.grpc.models.FlowRuleProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.onosproject.grpc.models.FlowRuleProto();
  }

  public static org.onosproject.grpc.models.FlowRuleProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlowRuleProto>
      PARSER = new com.google.protobuf.AbstractParser<FlowRuleProto>() {
    @java.lang.Override
    public FlowRuleProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlowRuleProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlowRuleProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlowRuleProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.onosproject.grpc.models.FlowRuleProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

