// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HostDescriptionProto.proto

package org.onosproject.grpc.models;

public final class HostDescriptionProto {
  private HostDescriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HostDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.HostDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hw_address = 1;</code>
     */
    java.lang.String getHwAddress();
    /**
     * <code>string hw_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getHwAddressBytes();

    /**
     * <code>uint32 vlan = 2;</code>
     */
    int getVlan();

    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    boolean hasLocation();
    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto getLocation();
    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder getLocationOrBuilder();

    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    java.util.List<java.lang.String>
        getIpAddressesList();
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    int getIpAddressesCount();
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    java.lang.String getIpAddresses(int index);
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressesBytes(int index);

    /**
     * <code>bool configured = 5;</code>
     */
    boolean getConfigured();

    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */
    boolean containsAnnotations(
        java.lang.String key);
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotations();
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotationsMap();
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    java.lang.String getAnnotationsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Corresponds to org.onosproject.net.host.HostDescription.
   * </pre>
   *
   * Protobuf type {@code proto.HostDescription}
   */
  public  static final class HostDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.HostDescription)
      HostDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HostDescription.newBuilder() to construct.
    private HostDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HostDescription() {
      hwAddress_ = "";
      vlan_ = 0;
      ipAddresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      configured_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HostDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hwAddress_ = s;
              break;
            }
            case 16: {

              vlan_ = input.readUInt32();
              break;
            }
            case 26: {
              org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                ipAddresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              ipAddresses_.add(s);
              break;
            }
            case 40: {

              configured_ = input.readBool();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                annotations_ = com.google.protobuf.MapField.newMapField(
                    AnnotationsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              annotations__ = input.readMessage(
                  AnnotationsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              annotations_.getMutableMap().put(
                  annotations__.getKey(), annotations__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          ipAddresses_ = ipAddresses_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAnnotations();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.HostDescriptionProto.HostDescription.class, org.onosproject.grpc.models.HostDescriptionProto.HostDescription.Builder.class);
    }

    private int bitField0_;
    public static final int HW_ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object hwAddress_;
    /**
     * <code>string hw_address = 1;</code>
     */
    public java.lang.String getHwAddress() {
      java.lang.Object ref = hwAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hwAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string hw_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHwAddressBytes() {
      java.lang.Object ref = hwAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hwAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VLAN_FIELD_NUMBER = 2;
    private int vlan_;
    /**
     * <code>uint32 vlan = 2;</code>
     */
    public int getVlan() {
      return vlan_;
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto location_;
    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    public org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto getLocation() {
      return location_ == null ? org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.getDefaultInstance() : location_;
    }
    /**
     * <code>.proto.HostLocationProto location = 3;</code>
     */
    public org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int IP_ADDRESSES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList ipAddresses_;
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIpAddressesList() {
      return ipAddresses_;
    }
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    public int getIpAddressesCount() {
      return ipAddresses_.size();
    }
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    public java.lang.String getIpAddresses(int index) {
      return ipAddresses_.get(index);
    }
    /**
     * <code>repeated string ip_addresses = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressesBytes(int index) {
      return ipAddresses_.getByteString(index);
    }

    public static final int CONFIGURED_FIELD_NUMBER = 5;
    private boolean configured_;
    /**
     * <code>bool configured = 5;</code>
     */
    public boolean getConfigured() {
      return configured_;
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 6;
    private static final class AnnotationsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_AnnotationsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> annotations_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAnnotations() {
      if (annotations_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AnnotationsDefaultEntryHolder.defaultEntry);
      }
      return annotations_;
    }

    public int getAnnotationsCount() {
      return internalGetAnnotations().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    public boolean containsAnnotations(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAnnotations().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
      return getAnnotationsMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
      return internalGetAnnotations().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    public java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 6;</code>
     */

    public java.lang.String getAnnotationsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHwAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hwAddress_);
      }
      if (vlan_ != 0) {
        output.writeUInt32(2, vlan_);
      }
      if (location_ != null) {
        output.writeMessage(3, getLocation());
      }
      for (int i = 0; i < ipAddresses_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ipAddresses_.getRaw(i));
      }
      if (configured_ != false) {
        output.writeBool(5, configured_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAnnotations(),
          AnnotationsDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHwAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hwAddress_);
      }
      if (vlan_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, vlan_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocation());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ipAddresses_.size(); i++) {
          dataSize += computeStringSizeNoTag(ipAddresses_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIpAddressesList().size();
      }
      if (configured_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, configured_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAnnotations().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        annotations__ = AnnotationsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, annotations__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onosproject.grpc.models.HostDescriptionProto.HostDescription)) {
        return super.equals(obj);
      }
      org.onosproject.grpc.models.HostDescriptionProto.HostDescription other = (org.onosproject.grpc.models.HostDescriptionProto.HostDescription) obj;

      boolean result = true;
      result = result && getHwAddress()
          .equals(other.getHwAddress());
      result = result && (getVlan()
          == other.getVlan());
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && getIpAddressesList()
          .equals(other.getIpAddressesList());
      result = result && (getConfigured()
          == other.getConfigured());
      result = result && internalGetAnnotations().equals(
          other.internalGetAnnotations());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HW_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getHwAddress().hashCode();
      hash = (37 * hash) + VLAN_FIELD_NUMBER;
      hash = (53 * hash) + getVlan();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      if (getIpAddressesCount() > 0) {
        hash = (37 * hash) + IP_ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddressesList().hashCode();
      }
      hash = (37 * hash) + CONFIGURED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConfigured());
      if (!internalGetAnnotations().getMap().isEmpty()) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAnnotations().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onosproject.grpc.models.HostDescriptionProto.HostDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Corresponds to org.onosproject.net.host.HostDescription.
     * </pre>
     *
     * Protobuf type {@code proto.HostDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.HostDescription)
        org.onosproject.grpc.models.HostDescriptionProto.HostDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.HostDescriptionProto.HostDescription.class, org.onosproject.grpc.models.HostDescriptionProto.HostDescription.Builder.class);
      }

      // Construct using org.onosproject.grpc.models.HostDescriptionProto.HostDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hwAddress_ = "";

        vlan_ = 0;

        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        ipAddresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        configured_ = false;

        internalGetMutableAnnotations().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onosproject.grpc.models.HostDescriptionProto.internal_static_proto_HostDescription_descriptor;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.HostDescriptionProto.HostDescription getDefaultInstanceForType() {
        return org.onosproject.grpc.models.HostDescriptionProto.HostDescription.getDefaultInstance();
      }

      @java.lang.Override
      public org.onosproject.grpc.models.HostDescriptionProto.HostDescription build() {
        org.onosproject.grpc.models.HostDescriptionProto.HostDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.HostDescriptionProto.HostDescription buildPartial() {
        org.onosproject.grpc.models.HostDescriptionProto.HostDescription result = new org.onosproject.grpc.models.HostDescriptionProto.HostDescription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.hwAddress_ = hwAddress_;
        result.vlan_ = vlan_;
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          ipAddresses_ = ipAddresses_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.ipAddresses_ = ipAddresses_;
        result.configured_ = configured_;
        result.annotations_ = internalGetAnnotations();
        result.annotations_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onosproject.grpc.models.HostDescriptionProto.HostDescription) {
          return mergeFrom((org.onosproject.grpc.models.HostDescriptionProto.HostDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onosproject.grpc.models.HostDescriptionProto.HostDescription other) {
        if (other == org.onosproject.grpc.models.HostDescriptionProto.HostDescription.getDefaultInstance()) return this;
        if (!other.getHwAddress().isEmpty()) {
          hwAddress_ = other.hwAddress_;
          onChanged();
        }
        if (other.getVlan() != 0) {
          setVlan(other.getVlan());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (!other.ipAddresses_.isEmpty()) {
          if (ipAddresses_.isEmpty()) {
            ipAddresses_ = other.ipAddresses_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIpAddressesIsMutable();
            ipAddresses_.addAll(other.ipAddresses_);
          }
          onChanged();
        }
        if (other.getConfigured() != false) {
          setConfigured(other.getConfigured());
        }
        internalGetMutableAnnotations().mergeFrom(
            other.internalGetAnnotations());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onosproject.grpc.models.HostDescriptionProto.HostDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onosproject.grpc.models.HostDescriptionProto.HostDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object hwAddress_ = "";
      /**
       * <code>string hw_address = 1;</code>
       */
      public java.lang.String getHwAddress() {
        java.lang.Object ref = hwAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hwAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hw_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHwAddressBytes() {
        java.lang.Object ref = hwAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hwAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hw_address = 1;</code>
       */
      public Builder setHwAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hwAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hw_address = 1;</code>
       */
      public Builder clearHwAddress() {
        
        hwAddress_ = getDefaultInstance().getHwAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string hw_address = 1;</code>
       */
      public Builder setHwAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hwAddress_ = value;
        onChanged();
        return this;
      }

      private int vlan_ ;
      /**
       * <code>uint32 vlan = 2;</code>
       */
      public int getVlan() {
        return vlan_;
      }
      /**
       * <code>uint32 vlan = 2;</code>
       */
      public Builder setVlan(int value) {
        
        vlan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 vlan = 2;</code>
       */
      public Builder clearVlan() {
        
        vlan_ = 0;
        onChanged();
        return this;
      }

      private org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder> locationBuilder_;
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public Builder setLocation(org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public Builder setLocation(
          org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public Builder mergeLocation(org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      public org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.proto.HostLocationProto location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProto.Builder, org.onosproject.grpc.models.HostLocationProtoOuterClass.HostLocationProtoOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private com.google.protobuf.LazyStringList ipAddresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIpAddressesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          ipAddresses_ = new com.google.protobuf.LazyStringArrayList(ipAddresses_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIpAddressesList() {
        return ipAddresses_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public int getIpAddressesCount() {
        return ipAddresses_.size();
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public java.lang.String getIpAddresses(int index) {
        return ipAddresses_.get(index);
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressesBytes(int index) {
        return ipAddresses_.getByteString(index);
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public Builder setIpAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIpAddressesIsMutable();
        ipAddresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public Builder addIpAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIpAddressesIsMutable();
        ipAddresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public Builder addAllIpAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureIpAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipAddresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public Builder clearIpAddresses() {
        ipAddresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ip_addresses = 4;</code>
       */
      public Builder addIpAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIpAddressesIsMutable();
        ipAddresses_.add(value);
        onChanged();
        return this;
      }

      private boolean configured_ ;
      /**
       * <code>bool configured = 5;</code>
       */
      public boolean getConfigured() {
        return configured_;
      }
      /**
       * <code>bool configured = 5;</code>
       */
      public Builder setConfigured(boolean value) {
        
        configured_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool configured = 5;</code>
       */
      public Builder clearConfigured() {
        
        configured_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> annotations_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAnnotations() {
        if (annotations_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        return annotations_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAnnotations() {
        onChanged();;
        if (annotations_ == null) {
          annotations_ = com.google.protobuf.MapField.newMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        if (!annotations_.isMutable()) {
          annotations_ = annotations_.copy();
        }
        return annotations_;
      }

      public int getAnnotationsCount() {
        return internalGetAnnotations().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public boolean containsAnnotations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAnnotations().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAnnotationsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
        return getAnnotationsMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
        return internalGetAnnotations().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public java.lang.String getAnnotationsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public java.lang.String getAnnotationsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAnnotations() {
        internalGetMutableAnnotations().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public Builder removeAnnotations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAnnotations() {
        return internalGetMutableAnnotations().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */
      public Builder putAnnotations(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 6;</code>
       */

      public Builder putAllAnnotations(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAnnotations().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.HostDescription)
    }

    // @@protoc_insertion_point(class_scope:proto.HostDescription)
    private static final org.onosproject.grpc.models.HostDescriptionProto.HostDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onosproject.grpc.models.HostDescriptionProto.HostDescription();
    }

    public static org.onosproject.grpc.models.HostDescriptionProto.HostDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HostDescription>
        PARSER = new com.google.protobuf.AbstractParser<HostDescription>() {
      @java.lang.Override
      public HostDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HostDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HostDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HostDescription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.HostDescriptionProto.HostDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HostDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HostDescription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HostDescription_AnnotationsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HostDescription_AnnotationsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032HostDescriptionProto.proto\022\005proto\032\027Hos" +
      "tLocationProto.proto\"\373\001\n\017HostDescription" +
      "\022\022\n\nhw_address\030\001 \001(\t\022\014\n\004vlan\030\002 \001(\r\022*\n\010lo" +
      "cation\030\003 \001(\0132\030.proto.HostLocationProto\022\024" +
      "\n\014ip_addresses\030\004 \003(\t\022\022\n\nconfigured\030\005 \001(\010" +
      "\022<\n\013annotations\030\006 \003(\0132\'.proto.HostDescri" +
      "ption.AnnotationsEntry\0322\n\020AnnotationsEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\035\n\033or" +
      "g.onosproject.grpc.modelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.onosproject.grpc.models.HostLocationProtoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_HostDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_HostDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HostDescription_descriptor,
        new java.lang.String[] { "HwAddress", "Vlan", "Location", "IpAddresses", "Configured", "Annotations", });
    internal_static_proto_HostDescription_AnnotationsEntry_descriptor =
      internal_static_proto_HostDescription_descriptor.getNestedTypes().get(0);
    internal_static_proto_HostDescription_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HostDescription_AnnotationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.onosproject.grpc.models.HostLocationProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
