// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeterProto.proto

package org.onosproject.grpc.models;

public final class MeterProtoOuterClass {
  private MeterProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeterProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MeterProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>uint64 meter_id = 2;</code>
     */
    long getMeterId();

    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    boolean hasApplicationId();
    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto getApplicationId();
    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder getApplicationIdOrBuilder();

    /**
     * <code>.proto.MeterUnitProto unit = 4;</code>
     */
    int getUnitValue();
    /**
     * <code>.proto.MeterUnitProto unit = 4;</code>
     */
    org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto getUnit();

    /**
     * <code>bool is_burst = 5;</code>
     */
    boolean getIsBurst();

    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto> 
        getBandsList();
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    org.onosproject.grpc.models.BandProtoOuterClass.BandProto getBands(int index);
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    int getBandsCount();
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    java.util.List<? extends org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder> 
        getBandsOrBuilderList();
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder getBandsOrBuilder(
        int index);

    /**
     * <code>.proto.MeterStateProto state = 7;</code>
     */
    int getStateValue();
    /**
     * <code>.proto.MeterStateProto state = 7;</code>
     */
    org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto getState();

    /**
     * <code>uint64 life = 8;</code>
     */
    long getLife();

    /**
     * <code>uint64 reference_count = 9;</code>
     */
    long getReferenceCount();

    /**
     * <code>uint64 packets_seen = 10;</code>
     */
    long getPacketsSeen();

    /**
     * <code>uint64 bytes_seen = 11;</code>
     */
    long getBytesSeen();
  }
  /**
   * Protobuf type {@code proto.MeterProto}
   */
  public  static final class MeterProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MeterProto)
      MeterProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MeterProto.newBuilder() to construct.
    private MeterProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MeterProto() {
      deviceId_ = "";
      meterId_ = 0L;
      unit_ = 0;
      isBurst_ = false;
      bands_ = java.util.Collections.emptyList();
      state_ = 0;
      life_ = 0L;
      referenceCount_ = 0L;
      packetsSeen_ = 0L;
      bytesSeen_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MeterProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 16: {

              meterId_ = input.readUInt64();
              break;
            }
            case 26: {
              org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder subBuilder = null;
              if (applicationId_ != null) {
                subBuilder = applicationId_.toBuilder();
              }
              applicationId_ = input.readMessage(org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(applicationId_);
                applicationId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            case 40: {

              isBurst_ = input.readBool();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                bands_ = new java.util.ArrayList<org.onosproject.grpc.models.BandProtoOuterClass.BandProto>();
                mutable_bitField0_ |= 0x00000020;
              }
              bands_.add(
                  input.readMessage(org.onosproject.grpc.models.BandProtoOuterClass.BandProto.parser(), extensionRegistry));
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 64: {

              life_ = input.readUInt64();
              break;
            }
            case 72: {

              referenceCount_ = input.readUInt64();
              break;
            }
            case 80: {

              packetsSeen_ = input.readUInt64();
              break;
            }
            case 88: {

              bytesSeen_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          bands_ = java.util.Collections.unmodifiableList(bands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.MeterProtoOuterClass.internal_static_proto_MeterProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.MeterProtoOuterClass.internal_static_proto_MeterProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.class, org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.Builder.class);
    }

    private int bitField0_;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METER_ID_FIELD_NUMBER = 2;
    private long meterId_;
    /**
     * <code>uint64 meter_id = 2;</code>
     */
    public long getMeterId() {
      return meterId_;
    }

    public static final int APPLICATION_ID_FIELD_NUMBER = 3;
    private org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto applicationId_;
    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    public boolean hasApplicationId() {
      return applicationId_ != null;
    }
    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    public org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto getApplicationId() {
      return applicationId_ == null ? org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.getDefaultInstance() : applicationId_;
    }
    /**
     * <code>.proto.ApplicationIdProto application_id = 3;</code>
     */
    public org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder getApplicationIdOrBuilder() {
      return getApplicationId();
    }

    public static final int UNIT_FIELD_NUMBER = 4;
    private int unit_;
    /**
     * <code>.proto.MeterUnitProto unit = 4;</code>
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.proto.MeterUnitProto unit = 4;</code>
     */
    public org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto getUnit() {
      @SuppressWarnings("deprecation")
      org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto result = org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.valueOf(unit_);
      return result == null ? org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.UNRECOGNIZED : result;
    }

    public static final int IS_BURST_FIELD_NUMBER = 5;
    private boolean isBurst_;
    /**
     * <code>bool is_burst = 5;</code>
     */
    public boolean getIsBurst() {
      return isBurst_;
    }

    public static final int BANDS_FIELD_NUMBER = 6;
    private java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto> bands_;
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    public java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto> getBandsList() {
      return bands_;
    }
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    public java.util.List<? extends org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder> 
        getBandsOrBuilderList() {
      return bands_;
    }
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    public int getBandsCount() {
      return bands_.size();
    }
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    public org.onosproject.grpc.models.BandProtoOuterClass.BandProto getBands(int index) {
      return bands_.get(index);
    }
    /**
     * <code>repeated .proto.BandProto bands = 6;</code>
     */
    public org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder getBandsOrBuilder(
        int index) {
      return bands_.get(index);
    }

    public static final int STATE_FIELD_NUMBER = 7;
    private int state_;
    /**
     * <code>.proto.MeterStateProto state = 7;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.proto.MeterStateProto state = 7;</code>
     */
    public org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto getState() {
      @SuppressWarnings("deprecation")
      org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto result = org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.valueOf(state_);
      return result == null ? org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.UNRECOGNIZED : result;
    }

    public static final int LIFE_FIELD_NUMBER = 8;
    private long life_;
    /**
     * <code>uint64 life = 8;</code>
     */
    public long getLife() {
      return life_;
    }

    public static final int REFERENCE_COUNT_FIELD_NUMBER = 9;
    private long referenceCount_;
    /**
     * <code>uint64 reference_count = 9;</code>
     */
    public long getReferenceCount() {
      return referenceCount_;
    }

    public static final int PACKETS_SEEN_FIELD_NUMBER = 10;
    private long packetsSeen_;
    /**
     * <code>uint64 packets_seen = 10;</code>
     */
    public long getPacketsSeen() {
      return packetsSeen_;
    }

    public static final int BYTES_SEEN_FIELD_NUMBER = 11;
    private long bytesSeen_;
    /**
     * <code>uint64 bytes_seen = 11;</code>
     */
    public long getBytesSeen() {
      return bytesSeen_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (meterId_ != 0L) {
        output.writeUInt64(2, meterId_);
      }
      if (applicationId_ != null) {
        output.writeMessage(3, getApplicationId());
      }
      if (unit_ != org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.PKTS_PER_SEC.getNumber()) {
        output.writeEnum(4, unit_);
      }
      if (isBurst_ != false) {
        output.writeBool(5, isBurst_);
      }
      for (int i = 0; i < bands_.size(); i++) {
        output.writeMessage(6, bands_.get(i));
      }
      if (state_ != org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.PENDING_ADD.getNumber()) {
        output.writeEnum(7, state_);
      }
      if (life_ != 0L) {
        output.writeUInt64(8, life_);
      }
      if (referenceCount_ != 0L) {
        output.writeUInt64(9, referenceCount_);
      }
      if (packetsSeen_ != 0L) {
        output.writeUInt64(10, packetsSeen_);
      }
      if (bytesSeen_ != 0L) {
        output.writeUInt64(11, bytesSeen_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (meterId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, meterId_);
      }
      if (applicationId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getApplicationId());
      }
      if (unit_ != org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.PKTS_PER_SEC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, unit_);
      }
      if (isBurst_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isBurst_);
      }
      for (int i = 0; i < bands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, bands_.get(i));
      }
      if (state_ != org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.PENDING_ADD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, state_);
      }
      if (life_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, life_);
      }
      if (referenceCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, referenceCount_);
      }
      if (packetsSeen_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, packetsSeen_);
      }
      if (bytesSeen_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, bytesSeen_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto)) {
        return super.equals(obj);
      }
      org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto other = (org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && (getMeterId()
          == other.getMeterId());
      result = result && (hasApplicationId() == other.hasApplicationId());
      if (hasApplicationId()) {
        result = result && getApplicationId()
            .equals(other.getApplicationId());
      }
      result = result && unit_ == other.unit_;
      result = result && (getIsBurst()
          == other.getIsBurst());
      result = result && getBandsList()
          .equals(other.getBandsList());
      result = result && state_ == other.state_;
      result = result && (getLife()
          == other.getLife());
      result = result && (getReferenceCount()
          == other.getReferenceCount());
      result = result && (getPacketsSeen()
          == other.getPacketsSeen());
      result = result && (getBytesSeen()
          == other.getBytesSeen());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + METER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMeterId());
      if (hasApplicationId()) {
        hash = (37 * hash) + APPLICATION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationId().hashCode();
      }
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (37 * hash) + IS_BURST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsBurst());
      if (getBandsCount() > 0) {
        hash = (37 * hash) + BANDS_FIELD_NUMBER;
        hash = (53 * hash) + getBandsList().hashCode();
      }
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + LIFE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLife());
      hash = (37 * hash) + REFERENCE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReferenceCount());
      hash = (37 * hash) + PACKETS_SEEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsSeen());
      hash = (37 * hash) + BYTES_SEEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBytesSeen());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MeterProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MeterProto)
        org.onosproject.grpc.models.MeterProtoOuterClass.MeterProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.MeterProtoOuterClass.internal_static_proto_MeterProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.MeterProtoOuterClass.internal_static_proto_MeterProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.class, org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.Builder.class);
      }

      // Construct using org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBandsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        meterId_ = 0L;

        if (applicationIdBuilder_ == null) {
          applicationId_ = null;
        } else {
          applicationId_ = null;
          applicationIdBuilder_ = null;
        }
        unit_ = 0;

        isBurst_ = false;

        if (bandsBuilder_ == null) {
          bands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          bandsBuilder_.clear();
        }
        state_ = 0;

        life_ = 0L;

        referenceCount_ = 0L;

        packetsSeen_ = 0L;

        bytesSeen_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onosproject.grpc.models.MeterProtoOuterClass.internal_static_proto_MeterProto_descriptor;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto getDefaultInstanceForType() {
        return org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto build() {
        org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto buildPartial() {
        org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto result = new org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.deviceId_ = deviceId_;
        result.meterId_ = meterId_;
        if (applicationIdBuilder_ == null) {
          result.applicationId_ = applicationId_;
        } else {
          result.applicationId_ = applicationIdBuilder_.build();
        }
        result.unit_ = unit_;
        result.isBurst_ = isBurst_;
        if (bandsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            bands_ = java.util.Collections.unmodifiableList(bands_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.bands_ = bands_;
        } else {
          result.bands_ = bandsBuilder_.build();
        }
        result.state_ = state_;
        result.life_ = life_;
        result.referenceCount_ = referenceCount_;
        result.packetsSeen_ = packetsSeen_;
        result.bytesSeen_ = bytesSeen_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto) {
          return mergeFrom((org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto other) {
        if (other == org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getMeterId() != 0L) {
          setMeterId(other.getMeterId());
        }
        if (other.hasApplicationId()) {
          mergeApplicationId(other.getApplicationId());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        if (other.getIsBurst() != false) {
          setIsBurst(other.getIsBurst());
        }
        if (bandsBuilder_ == null) {
          if (!other.bands_.isEmpty()) {
            if (bands_.isEmpty()) {
              bands_ = other.bands_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureBandsIsMutable();
              bands_.addAll(other.bands_);
            }
            onChanged();
          }
        } else {
          if (!other.bands_.isEmpty()) {
            if (bandsBuilder_.isEmpty()) {
              bandsBuilder_.dispose();
              bandsBuilder_ = null;
              bands_ = other.bands_;
              bitField0_ = (bitField0_ & ~0x00000020);
              bandsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBandsFieldBuilder() : null;
            } else {
              bandsBuilder_.addAllMessages(other.bands_);
            }
          }
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getLife() != 0L) {
          setLife(other.getLife());
        }
        if (other.getReferenceCount() != 0L) {
          setReferenceCount(other.getReferenceCount());
        }
        if (other.getPacketsSeen() != 0L) {
          setPacketsSeen(other.getPacketsSeen());
        }
        if (other.getBytesSeen() != 0L) {
          setBytesSeen(other.getBytesSeen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private long meterId_ ;
      /**
       * <code>uint64 meter_id = 2;</code>
       */
      public long getMeterId() {
        return meterId_;
      }
      /**
       * <code>uint64 meter_id = 2;</code>
       */
      public Builder setMeterId(long value) {
        
        meterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 meter_id = 2;</code>
       */
      public Builder clearMeterId() {
        
        meterId_ = 0L;
        onChanged();
        return this;
      }

      private org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto applicationId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder> applicationIdBuilder_;
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public boolean hasApplicationId() {
        return applicationIdBuilder_ != null || applicationId_ != null;
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto getApplicationId() {
        if (applicationIdBuilder_ == null) {
          return applicationId_ == null ? org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.getDefaultInstance() : applicationId_;
        } else {
          return applicationIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public Builder setApplicationId(org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto value) {
        if (applicationIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationId_ = value;
          onChanged();
        } else {
          applicationIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public Builder setApplicationId(
          org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder builderForValue) {
        if (applicationIdBuilder_ == null) {
          applicationId_ = builderForValue.build();
          onChanged();
        } else {
          applicationIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public Builder mergeApplicationId(org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto value) {
        if (applicationIdBuilder_ == null) {
          if (applicationId_ != null) {
            applicationId_ =
              org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.newBuilder(applicationId_).mergeFrom(value).buildPartial();
          } else {
            applicationId_ = value;
          }
          onChanged();
        } else {
          applicationIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public Builder clearApplicationId() {
        if (applicationIdBuilder_ == null) {
          applicationId_ = null;
          onChanged();
        } else {
          applicationId_ = null;
          applicationIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder getApplicationIdBuilder() {
        
        onChanged();
        return getApplicationIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      public org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder getApplicationIdOrBuilder() {
        if (applicationIdBuilder_ != null) {
          return applicationIdBuilder_.getMessageOrBuilder();
        } else {
          return applicationId_ == null ?
              org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.getDefaultInstance() : applicationId_;
        }
      }
      /**
       * <code>.proto.ApplicationIdProto application_id = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder> 
          getApplicationIdFieldBuilder() {
        if (applicationIdBuilder_ == null) {
          applicationIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProto.Builder, org.onosproject.grpc.models.ApplicationIdProtoOuterClass.ApplicationIdProtoOrBuilder>(
                  getApplicationId(),
                  getParentForChildren(),
                  isClean());
          applicationId_ = null;
        }
        return applicationIdBuilder_;
      }

      private int unit_ = 0;
      /**
       * <code>.proto.MeterUnitProto unit = 4;</code>
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.proto.MeterUnitProto unit = 4;</code>
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.MeterUnitProto unit = 4;</code>
       */
      public org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto getUnit() {
        @SuppressWarnings("deprecation")
        org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto result = org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.valueOf(unit_);
        return result == null ? org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.MeterUnitProto unit = 4;</code>
       */
      public Builder setUnit(org.onosproject.grpc.models.MeterEnumsProto.MeterUnitProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.MeterUnitProto unit = 4;</code>
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }

      private boolean isBurst_ ;
      /**
       * <code>bool is_burst = 5;</code>
       */
      public boolean getIsBurst() {
        return isBurst_;
      }
      /**
       * <code>bool is_burst = 5;</code>
       */
      public Builder setIsBurst(boolean value) {
        
        isBurst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_burst = 5;</code>
       */
      public Builder clearIsBurst() {
        
        isBurst_ = false;
        onChanged();
        return this;
      }

      private java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto> bands_ =
        java.util.Collections.emptyList();
      private void ensureBandsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          bands_ = new java.util.ArrayList<org.onosproject.grpc.models.BandProtoOuterClass.BandProto>(bands_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onosproject.grpc.models.BandProtoOuterClass.BandProto, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder, org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder> bandsBuilder_;

      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto> getBandsList() {
        if (bandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bands_);
        } else {
          return bandsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public int getBandsCount() {
        if (bandsBuilder_ == null) {
          return bands_.size();
        } else {
          return bandsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public org.onosproject.grpc.models.BandProtoOuterClass.BandProto getBands(int index) {
        if (bandsBuilder_ == null) {
          return bands_.get(index);
        } else {
          return bandsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder setBands(
          int index, org.onosproject.grpc.models.BandProtoOuterClass.BandProto value) {
        if (bandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBandsIsMutable();
          bands_.set(index, value);
          onChanged();
        } else {
          bandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder setBands(
          int index, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder builderForValue) {
        if (bandsBuilder_ == null) {
          ensureBandsIsMutable();
          bands_.set(index, builderForValue.build());
          onChanged();
        } else {
          bandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder addBands(org.onosproject.grpc.models.BandProtoOuterClass.BandProto value) {
        if (bandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBandsIsMutable();
          bands_.add(value);
          onChanged();
        } else {
          bandsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder addBands(
          int index, org.onosproject.grpc.models.BandProtoOuterClass.BandProto value) {
        if (bandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBandsIsMutable();
          bands_.add(index, value);
          onChanged();
        } else {
          bandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder addBands(
          org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder builderForValue) {
        if (bandsBuilder_ == null) {
          ensureBandsIsMutable();
          bands_.add(builderForValue.build());
          onChanged();
        } else {
          bandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder addBands(
          int index, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder builderForValue) {
        if (bandsBuilder_ == null) {
          ensureBandsIsMutable();
          bands_.add(index, builderForValue.build());
          onChanged();
        } else {
          bandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder addAllBands(
          java.lang.Iterable<? extends org.onosproject.grpc.models.BandProtoOuterClass.BandProto> values) {
        if (bandsBuilder_ == null) {
          ensureBandsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bands_);
          onChanged();
        } else {
          bandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder clearBands() {
        if (bandsBuilder_ == null) {
          bands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          bandsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public Builder removeBands(int index) {
        if (bandsBuilder_ == null) {
          ensureBandsIsMutable();
          bands_.remove(index);
          onChanged();
        } else {
          bandsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder getBandsBuilder(
          int index) {
        return getBandsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder getBandsOrBuilder(
          int index) {
        if (bandsBuilder_ == null) {
          return bands_.get(index);  } else {
          return bandsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public java.util.List<? extends org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder> 
           getBandsOrBuilderList() {
        if (bandsBuilder_ != null) {
          return bandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bands_);
        }
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder addBandsBuilder() {
        return getBandsFieldBuilder().addBuilder(
            org.onosproject.grpc.models.BandProtoOuterClass.BandProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder addBandsBuilder(
          int index) {
        return getBandsFieldBuilder().addBuilder(
            index, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.BandProto bands = 6;</code>
       */
      public java.util.List<org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder> 
           getBandsBuilderList() {
        return getBandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onosproject.grpc.models.BandProtoOuterClass.BandProto, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder, org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder> 
          getBandsFieldBuilder() {
        if (bandsBuilder_ == null) {
          bandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.onosproject.grpc.models.BandProtoOuterClass.BandProto, org.onosproject.grpc.models.BandProtoOuterClass.BandProto.Builder, org.onosproject.grpc.models.BandProtoOuterClass.BandProtoOrBuilder>(
                  bands_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          bands_ = null;
        }
        return bandsBuilder_;
      }

      private int state_ = 0;
      /**
       * <code>.proto.MeterStateProto state = 7;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>.proto.MeterStateProto state = 7;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.MeterStateProto state = 7;</code>
       */
      public org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto getState() {
        @SuppressWarnings("deprecation")
        org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto result = org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.valueOf(state_);
        return result == null ? org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.MeterStateProto state = 7;</code>
       */
      public Builder setState(org.onosproject.grpc.models.MeterEnumsProto.MeterStateProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.MeterStateProto state = 7;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private long life_ ;
      /**
       * <code>uint64 life = 8;</code>
       */
      public long getLife() {
        return life_;
      }
      /**
       * <code>uint64 life = 8;</code>
       */
      public Builder setLife(long value) {
        
        life_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 life = 8;</code>
       */
      public Builder clearLife() {
        
        life_ = 0L;
        onChanged();
        return this;
      }

      private long referenceCount_ ;
      /**
       * <code>uint64 reference_count = 9;</code>
       */
      public long getReferenceCount() {
        return referenceCount_;
      }
      /**
       * <code>uint64 reference_count = 9;</code>
       */
      public Builder setReferenceCount(long value) {
        
        referenceCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 reference_count = 9;</code>
       */
      public Builder clearReferenceCount() {
        
        referenceCount_ = 0L;
        onChanged();
        return this;
      }

      private long packetsSeen_ ;
      /**
       * <code>uint64 packets_seen = 10;</code>
       */
      public long getPacketsSeen() {
        return packetsSeen_;
      }
      /**
       * <code>uint64 packets_seen = 10;</code>
       */
      public Builder setPacketsSeen(long value) {
        
        packetsSeen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 packets_seen = 10;</code>
       */
      public Builder clearPacketsSeen() {
        
        packetsSeen_ = 0L;
        onChanged();
        return this;
      }

      private long bytesSeen_ ;
      /**
       * <code>uint64 bytes_seen = 11;</code>
       */
      public long getBytesSeen() {
        return bytesSeen_;
      }
      /**
       * <code>uint64 bytes_seen = 11;</code>
       */
      public Builder setBytesSeen(long value) {
        
        bytesSeen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 bytes_seen = 11;</code>
       */
      public Builder clearBytesSeen() {
        
        bytesSeen_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MeterProto)
    }

    // @@protoc_insertion_point(class_scope:proto.MeterProto)
    private static final org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto();
    }

    public static org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MeterProto>
        PARSER = new com.google.protobuf.AbstractParser<MeterProto>() {
      @java.lang.Override
      public MeterProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MeterProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MeterProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MeterProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.MeterProtoOuterClass.MeterProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MeterProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MeterProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MeterProto.proto\022\005proto\032\017BandProto.pro" +
      "to\032\025MeterEnumsProto.proto\032\030ApplicationId" +
      "Proto.proto\"\264\002\n\nMeterProto\022\021\n\tdevice_id\030" +
      "\001 \001(\t\022\020\n\010meter_id\030\002 \001(\004\0221\n\016application_i" +
      "d\030\003 \001(\0132\031.proto.ApplicationIdProto\022#\n\004un" +
      "it\030\004 \001(\0162\025.proto.MeterUnitProto\022\020\n\010is_bu" +
      "rst\030\005 \001(\010\022\037\n\005bands\030\006 \003(\0132\020.proto.BandPro" +
      "to\022%\n\005state\030\007 \001(\0162\026.proto.MeterStateProt" +
      "o\022\014\n\004life\030\010 \001(\004\022\027\n\017reference_count\030\t \001(\004" +
      "\022\024\n\014packets_seen\030\n \001(\004\022\022\n\nbytes_seen\030\013 \001" +
      "(\004B\035\n\033org.onosproject.grpc.modelsb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.onosproject.grpc.models.BandProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.MeterEnumsProto.getDescriptor(),
          org.onosproject.grpc.models.ApplicationIdProtoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_MeterProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MeterProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MeterProto_descriptor,
        new java.lang.String[] { "DeviceId", "MeterId", "ApplicationId", "Unit", "IsBurst", "Bands", "State", "Life", "ReferenceCount", "PacketsSeen", "BytesSeen", });
    org.onosproject.grpc.models.BandProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.MeterEnumsProto.getDescriptor();
    org.onosproject.grpc.models.ApplicationIdProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
