// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PortStatisticsProto.proto

package org.onosproject.grpc.models;

public final class PortStatisticsProtoOuterClass {
  private PortStatisticsProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PortStatisticsProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PortStatisticsProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 port = 1;</code>
     */
    int getPort();

    /**
     * <code>int64 packets_received = 2;</code>
     */
    long getPacketsReceived();

    /**
     * <code>int64 packets_sent = 3;</code>
     */
    long getPacketsSent();

    /**
     * <code>int64 bytes_received = 4;</code>
     */
    long getBytesReceived();

    /**
     * <code>int64 bytes_sent = 5;</code>
     */
    long getBytesSent();

    /**
     * <code>int64 packets_rx_dropped = 6;</code>
     */
    long getPacketsRxDropped();

    /**
     * <code>int64 packets_tx_dropped = 7;</code>
     */
    long getPacketsTxDropped();

    /**
     * <code>int64 packets_rx_errors = 8;</code>
     */
    long getPacketsRxErrors();

    /**
     * <code>int64 packets_tx_errors = 9;</code>
     */
    long getPacketsTxErrors();

    /**
     * <code>int64 duration_sec = 10;</code>
     */
    long getDurationSec();

    /**
     * <code>int64 duration_nano = 11;</code>
     */
    long getDurationNano();

    /**
     * <pre>
     * TODO add all other fields
     * </pre>
     *
     * <code>bool is_zero = 12;</code>
     */
    boolean getIsZero();
  }
  /**
   * Protobuf type {@code proto.PortStatisticsProto}
   */
  public  static final class PortStatisticsProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PortStatisticsProto)
      PortStatisticsProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PortStatisticsProto.newBuilder() to construct.
    private PortStatisticsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PortStatisticsProto() {
      port_ = 0;
      packetsReceived_ = 0L;
      packetsSent_ = 0L;
      bytesReceived_ = 0L;
      bytesSent_ = 0L;
      packetsRxDropped_ = 0L;
      packetsTxDropped_ = 0L;
      packetsRxErrors_ = 0L;
      packetsTxErrors_ = 0L;
      durationSec_ = 0L;
      durationNano_ = 0L;
      isZero_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PortStatisticsProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              port_ = input.readInt32();
              break;
            }
            case 16: {

              packetsReceived_ = input.readInt64();
              break;
            }
            case 24: {

              packetsSent_ = input.readInt64();
              break;
            }
            case 32: {

              bytesReceived_ = input.readInt64();
              break;
            }
            case 40: {

              bytesSent_ = input.readInt64();
              break;
            }
            case 48: {

              packetsRxDropped_ = input.readInt64();
              break;
            }
            case 56: {

              packetsTxDropped_ = input.readInt64();
              break;
            }
            case 64: {

              packetsRxErrors_ = input.readInt64();
              break;
            }
            case 72: {

              packetsTxErrors_ = input.readInt64();
              break;
            }
            case 80: {

              durationSec_ = input.readInt64();
              break;
            }
            case 88: {

              durationNano_ = input.readInt64();
              break;
            }
            case 96: {

              isZero_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.internal_static_proto_PortStatisticsProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.internal_static_proto_PortStatisticsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.class, org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.Builder.class);
    }

    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int PACKETS_RECEIVED_FIELD_NUMBER = 2;
    private long packetsReceived_;
    /**
     * <code>int64 packets_received = 2;</code>
     */
    public long getPacketsReceived() {
      return packetsReceived_;
    }

    public static final int PACKETS_SENT_FIELD_NUMBER = 3;
    private long packetsSent_;
    /**
     * <code>int64 packets_sent = 3;</code>
     */
    public long getPacketsSent() {
      return packetsSent_;
    }

    public static final int BYTES_RECEIVED_FIELD_NUMBER = 4;
    private long bytesReceived_;
    /**
     * <code>int64 bytes_received = 4;</code>
     */
    public long getBytesReceived() {
      return bytesReceived_;
    }

    public static final int BYTES_SENT_FIELD_NUMBER = 5;
    private long bytesSent_;
    /**
     * <code>int64 bytes_sent = 5;</code>
     */
    public long getBytesSent() {
      return bytesSent_;
    }

    public static final int PACKETS_RX_DROPPED_FIELD_NUMBER = 6;
    private long packetsRxDropped_;
    /**
     * <code>int64 packets_rx_dropped = 6;</code>
     */
    public long getPacketsRxDropped() {
      return packetsRxDropped_;
    }

    public static final int PACKETS_TX_DROPPED_FIELD_NUMBER = 7;
    private long packetsTxDropped_;
    /**
     * <code>int64 packets_tx_dropped = 7;</code>
     */
    public long getPacketsTxDropped() {
      return packetsTxDropped_;
    }

    public static final int PACKETS_RX_ERRORS_FIELD_NUMBER = 8;
    private long packetsRxErrors_;
    /**
     * <code>int64 packets_rx_errors = 8;</code>
     */
    public long getPacketsRxErrors() {
      return packetsRxErrors_;
    }

    public static final int PACKETS_TX_ERRORS_FIELD_NUMBER = 9;
    private long packetsTxErrors_;
    /**
     * <code>int64 packets_tx_errors = 9;</code>
     */
    public long getPacketsTxErrors() {
      return packetsTxErrors_;
    }

    public static final int DURATION_SEC_FIELD_NUMBER = 10;
    private long durationSec_;
    /**
     * <code>int64 duration_sec = 10;</code>
     */
    public long getDurationSec() {
      return durationSec_;
    }

    public static final int DURATION_NANO_FIELD_NUMBER = 11;
    private long durationNano_;
    /**
     * <code>int64 duration_nano = 11;</code>
     */
    public long getDurationNano() {
      return durationNano_;
    }

    public static final int IS_ZERO_FIELD_NUMBER = 12;
    private boolean isZero_;
    /**
     * <pre>
     * TODO add all other fields
     * </pre>
     *
     * <code>bool is_zero = 12;</code>
     */
    public boolean getIsZero() {
      return isZero_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (port_ != 0) {
        output.writeInt32(1, port_);
      }
      if (packetsReceived_ != 0L) {
        output.writeInt64(2, packetsReceived_);
      }
      if (packetsSent_ != 0L) {
        output.writeInt64(3, packetsSent_);
      }
      if (bytesReceived_ != 0L) {
        output.writeInt64(4, bytesReceived_);
      }
      if (bytesSent_ != 0L) {
        output.writeInt64(5, bytesSent_);
      }
      if (packetsRxDropped_ != 0L) {
        output.writeInt64(6, packetsRxDropped_);
      }
      if (packetsTxDropped_ != 0L) {
        output.writeInt64(7, packetsTxDropped_);
      }
      if (packetsRxErrors_ != 0L) {
        output.writeInt64(8, packetsRxErrors_);
      }
      if (packetsTxErrors_ != 0L) {
        output.writeInt64(9, packetsTxErrors_);
      }
      if (durationSec_ != 0L) {
        output.writeInt64(10, durationSec_);
      }
      if (durationNano_ != 0L) {
        output.writeInt64(11, durationNano_);
      }
      if (isZero_ != false) {
        output.writeBool(12, isZero_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (packetsReceived_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, packetsReceived_);
      }
      if (packetsSent_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, packetsSent_);
      }
      if (bytesReceived_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, bytesReceived_);
      }
      if (bytesSent_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, bytesSent_);
      }
      if (packetsRxDropped_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, packetsRxDropped_);
      }
      if (packetsTxDropped_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, packetsTxDropped_);
      }
      if (packetsRxErrors_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, packetsRxErrors_);
      }
      if (packetsTxErrors_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, packetsTxErrors_);
      }
      if (durationSec_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, durationSec_);
      }
      if (durationNano_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, durationNano_);
      }
      if (isZero_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, isZero_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto)) {
        return super.equals(obj);
      }
      org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto other = (org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto) obj;

      boolean result = true;
      result = result && (getPort()
          == other.getPort());
      result = result && (getPacketsReceived()
          == other.getPacketsReceived());
      result = result && (getPacketsSent()
          == other.getPacketsSent());
      result = result && (getBytesReceived()
          == other.getBytesReceived());
      result = result && (getBytesSent()
          == other.getBytesSent());
      result = result && (getPacketsRxDropped()
          == other.getPacketsRxDropped());
      result = result && (getPacketsTxDropped()
          == other.getPacketsTxDropped());
      result = result && (getPacketsRxErrors()
          == other.getPacketsRxErrors());
      result = result && (getPacketsTxErrors()
          == other.getPacketsTxErrors());
      result = result && (getDurationSec()
          == other.getDurationSec());
      result = result && (getDurationNano()
          == other.getDurationNano());
      result = result && (getIsZero()
          == other.getIsZero());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + PACKETS_RECEIVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsReceived());
      hash = (37 * hash) + PACKETS_SENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsSent());
      hash = (37 * hash) + BYTES_RECEIVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBytesReceived());
      hash = (37 * hash) + BYTES_SENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBytesSent());
      hash = (37 * hash) + PACKETS_RX_DROPPED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsRxDropped());
      hash = (37 * hash) + PACKETS_TX_DROPPED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsTxDropped());
      hash = (37 * hash) + PACKETS_RX_ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsRxErrors());
      hash = (37 * hash) + PACKETS_TX_ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketsTxErrors());
      hash = (37 * hash) + DURATION_SEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDurationSec());
      hash = (37 * hash) + DURATION_NANO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDurationNano());
      hash = (37 * hash) + IS_ZERO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsZero());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PortStatisticsProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PortStatisticsProto)
        org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.internal_static_proto_PortStatisticsProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.internal_static_proto_PortStatisticsProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.class, org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.Builder.class);
      }

      // Construct using org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        port_ = 0;

        packetsReceived_ = 0L;

        packetsSent_ = 0L;

        bytesReceived_ = 0L;

        bytesSent_ = 0L;

        packetsRxDropped_ = 0L;

        packetsTxDropped_ = 0L;

        packetsRxErrors_ = 0L;

        packetsTxErrors_ = 0L;

        durationSec_ = 0L;

        durationNano_ = 0L;

        isZero_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.internal_static_proto_PortStatisticsProto_descriptor;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto getDefaultInstanceForType() {
        return org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto build() {
        org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto buildPartial() {
        org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto result = new org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto(this);
        result.port_ = port_;
        result.packetsReceived_ = packetsReceived_;
        result.packetsSent_ = packetsSent_;
        result.bytesReceived_ = bytesReceived_;
        result.bytesSent_ = bytesSent_;
        result.packetsRxDropped_ = packetsRxDropped_;
        result.packetsTxDropped_ = packetsTxDropped_;
        result.packetsRxErrors_ = packetsRxErrors_;
        result.packetsTxErrors_ = packetsTxErrors_;
        result.durationSec_ = durationSec_;
        result.durationNano_ = durationNano_;
        result.isZero_ = isZero_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto) {
          return mergeFrom((org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto other) {
        if (other == org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto.getDefaultInstance()) return this;
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getPacketsReceived() != 0L) {
          setPacketsReceived(other.getPacketsReceived());
        }
        if (other.getPacketsSent() != 0L) {
          setPacketsSent(other.getPacketsSent());
        }
        if (other.getBytesReceived() != 0L) {
          setBytesReceived(other.getBytesReceived());
        }
        if (other.getBytesSent() != 0L) {
          setBytesSent(other.getBytesSent());
        }
        if (other.getPacketsRxDropped() != 0L) {
          setPacketsRxDropped(other.getPacketsRxDropped());
        }
        if (other.getPacketsTxDropped() != 0L) {
          setPacketsTxDropped(other.getPacketsTxDropped());
        }
        if (other.getPacketsRxErrors() != 0L) {
          setPacketsRxErrors(other.getPacketsRxErrors());
        }
        if (other.getPacketsTxErrors() != 0L) {
          setPacketsTxErrors(other.getPacketsTxErrors());
        }
        if (other.getDurationSec() != 0L) {
          setDurationSec(other.getDurationSec());
        }
        if (other.getDurationNano() != 0L) {
          setDurationNano(other.getDurationNano());
        }
        if (other.getIsZero() != false) {
          setIsZero(other.getIsZero());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 1;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private long packetsReceived_ ;
      /**
       * <code>int64 packets_received = 2;</code>
       */
      public long getPacketsReceived() {
        return packetsReceived_;
      }
      /**
       * <code>int64 packets_received = 2;</code>
       */
      public Builder setPacketsReceived(long value) {
        
        packetsReceived_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_received = 2;</code>
       */
      public Builder clearPacketsReceived() {
        
        packetsReceived_ = 0L;
        onChanged();
        return this;
      }

      private long packetsSent_ ;
      /**
       * <code>int64 packets_sent = 3;</code>
       */
      public long getPacketsSent() {
        return packetsSent_;
      }
      /**
       * <code>int64 packets_sent = 3;</code>
       */
      public Builder setPacketsSent(long value) {
        
        packetsSent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_sent = 3;</code>
       */
      public Builder clearPacketsSent() {
        
        packetsSent_ = 0L;
        onChanged();
        return this;
      }

      private long bytesReceived_ ;
      /**
       * <code>int64 bytes_received = 4;</code>
       */
      public long getBytesReceived() {
        return bytesReceived_;
      }
      /**
       * <code>int64 bytes_received = 4;</code>
       */
      public Builder setBytesReceived(long value) {
        
        bytesReceived_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 bytes_received = 4;</code>
       */
      public Builder clearBytesReceived() {
        
        bytesReceived_ = 0L;
        onChanged();
        return this;
      }

      private long bytesSent_ ;
      /**
       * <code>int64 bytes_sent = 5;</code>
       */
      public long getBytesSent() {
        return bytesSent_;
      }
      /**
       * <code>int64 bytes_sent = 5;</code>
       */
      public Builder setBytesSent(long value) {
        
        bytesSent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 bytes_sent = 5;</code>
       */
      public Builder clearBytesSent() {
        
        bytesSent_ = 0L;
        onChanged();
        return this;
      }

      private long packetsRxDropped_ ;
      /**
       * <code>int64 packets_rx_dropped = 6;</code>
       */
      public long getPacketsRxDropped() {
        return packetsRxDropped_;
      }
      /**
       * <code>int64 packets_rx_dropped = 6;</code>
       */
      public Builder setPacketsRxDropped(long value) {
        
        packetsRxDropped_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_rx_dropped = 6;</code>
       */
      public Builder clearPacketsRxDropped() {
        
        packetsRxDropped_ = 0L;
        onChanged();
        return this;
      }

      private long packetsTxDropped_ ;
      /**
       * <code>int64 packets_tx_dropped = 7;</code>
       */
      public long getPacketsTxDropped() {
        return packetsTxDropped_;
      }
      /**
       * <code>int64 packets_tx_dropped = 7;</code>
       */
      public Builder setPacketsTxDropped(long value) {
        
        packetsTxDropped_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_tx_dropped = 7;</code>
       */
      public Builder clearPacketsTxDropped() {
        
        packetsTxDropped_ = 0L;
        onChanged();
        return this;
      }

      private long packetsRxErrors_ ;
      /**
       * <code>int64 packets_rx_errors = 8;</code>
       */
      public long getPacketsRxErrors() {
        return packetsRxErrors_;
      }
      /**
       * <code>int64 packets_rx_errors = 8;</code>
       */
      public Builder setPacketsRxErrors(long value) {
        
        packetsRxErrors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_rx_errors = 8;</code>
       */
      public Builder clearPacketsRxErrors() {
        
        packetsRxErrors_ = 0L;
        onChanged();
        return this;
      }

      private long packetsTxErrors_ ;
      /**
       * <code>int64 packets_tx_errors = 9;</code>
       */
      public long getPacketsTxErrors() {
        return packetsTxErrors_;
      }
      /**
       * <code>int64 packets_tx_errors = 9;</code>
       */
      public Builder setPacketsTxErrors(long value) {
        
        packetsTxErrors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packets_tx_errors = 9;</code>
       */
      public Builder clearPacketsTxErrors() {
        
        packetsTxErrors_ = 0L;
        onChanged();
        return this;
      }

      private long durationSec_ ;
      /**
       * <code>int64 duration_sec = 10;</code>
       */
      public long getDurationSec() {
        return durationSec_;
      }
      /**
       * <code>int64 duration_sec = 10;</code>
       */
      public Builder setDurationSec(long value) {
        
        durationSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 duration_sec = 10;</code>
       */
      public Builder clearDurationSec() {
        
        durationSec_ = 0L;
        onChanged();
        return this;
      }

      private long durationNano_ ;
      /**
       * <code>int64 duration_nano = 11;</code>
       */
      public long getDurationNano() {
        return durationNano_;
      }
      /**
       * <code>int64 duration_nano = 11;</code>
       */
      public Builder setDurationNano(long value) {
        
        durationNano_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 duration_nano = 11;</code>
       */
      public Builder clearDurationNano() {
        
        durationNano_ = 0L;
        onChanged();
        return this;
      }

      private boolean isZero_ ;
      /**
       * <pre>
       * TODO add all other fields
       * </pre>
       *
       * <code>bool is_zero = 12;</code>
       */
      public boolean getIsZero() {
        return isZero_;
      }
      /**
       * <pre>
       * TODO add all other fields
       * </pre>
       *
       * <code>bool is_zero = 12;</code>
       */
      public Builder setIsZero(boolean value) {
        
        isZero_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * TODO add all other fields
       * </pre>
       *
       * <code>bool is_zero = 12;</code>
       */
      public Builder clearIsZero() {
        
        isZero_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.PortStatisticsProto)
    }

    // @@protoc_insertion_point(class_scope:proto.PortStatisticsProto)
    private static final org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto();
    }

    public static org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PortStatisticsProto>
        PARSER = new com.google.protobuf.AbstractParser<PortStatisticsProto>() {
      @java.lang.Override
      public PortStatisticsProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PortStatisticsProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PortStatisticsProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PortStatisticsProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.PortStatisticsProtoOuterClass.PortStatisticsProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PortStatisticsProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PortStatisticsProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PortStatisticsProto.proto\022\005proto\"\253\002\n\023P" +
      "ortStatisticsProto\022\014\n\004port\030\001 \001(\005\022\030\n\020pack" +
      "ets_received\030\002 \001(\003\022\024\n\014packets_sent\030\003 \001(\003" +
      "\022\026\n\016bytes_received\030\004 \001(\003\022\022\n\nbytes_sent\030\005" +
      " \001(\003\022\032\n\022packets_rx_dropped\030\006 \001(\003\022\032\n\022pack" +
      "ets_tx_dropped\030\007 \001(\003\022\031\n\021packets_rx_error" +
      "s\030\010 \001(\003\022\031\n\021packets_tx_errors\030\t \001(\003\022\024\n\014du" +
      "ration_sec\030\n \001(\003\022\025\n\rduration_nano\030\013 \001(\003\022" +
      "\017\n\007is_zero\030\014 \001(\010B\035\n\033org.onosproject.grpc" +
      ".modelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_PortStatisticsProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PortStatisticsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PortStatisticsProto_descriptor,
        new java.lang.String[] { "Port", "PacketsReceived", "PacketsSent", "BytesReceived", "BytesSent", "PacketsRxDropped", "PacketsTxDropped", "PacketsRxErrors", "PacketsTxErrors", "DurationSec", "DurationNano", "IsZero", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
