// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegionProto.proto

package org.onosproject.grpc.models;

public final class RegionProtoOuterClass {
  private RegionProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegionProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RegionProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string region_id = 1;</code>
     */
    java.lang.String getRegionId();
    /**
     * <code>string region_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getRegionIdBytes();

    /**
     * <code>.proto.RegionTypeProto type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.proto.RegionTypeProto type = 2;</code>
     */
    org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto getType();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> 
        getMastersList();
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getMasters(int index);
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    int getMastersCount();
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    java.util.List<? extends org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder> 
        getMastersOrBuilderList();
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder getMastersOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    boolean containsAnnotations(
        java.lang.String key);
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotations();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotationsMap();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    java.lang.String getAnnotationsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code proto.RegionProto}
   */
  public  static final class RegionProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.RegionProto)
      RegionProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegionProto.newBuilder() to construct.
    private RegionProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegionProto() {
      regionId_ = "";
      type_ = 0;
      name_ = "";
      masters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegionProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              regionId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                masters_ = new java.util.ArrayList<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet>();
                mutable_bitField0_ |= 0x00000008;
              }
              masters_.add(
                  input.readMessage(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                annotations_ = com.google.protobuf.MapField.newMapField(
                    AnnotationsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              annotations__ = input.readMessage(
                  AnnotationsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              annotations_.getMutableMap().put(
                  annotations__.getKey(), annotations__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          masters_ = java.util.Collections.unmodifiableList(masters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAnnotations();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.class, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.Builder.class);
    }

    public interface NodeIdSetOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.RegionProto.NodeIdSet)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string node_id = 1;</code>
       */
      java.util.List<java.lang.String>
          getNodeIdList();
      /**
       * <code>repeated string node_id = 1;</code>
       */
      int getNodeIdCount();
      /**
       * <code>repeated string node_id = 1;</code>
       */
      java.lang.String getNodeId(int index);
      /**
       * <code>repeated string node_id = 1;</code>
       */
      com.google.protobuf.ByteString
          getNodeIdBytes(int index);
    }
    /**
     * <pre>
     * List&lt;Set&lt;NodeId&gt;&gt; masters();
     * Since masters is a list of set of NodeIds,
     * the following message is required.
     * </pre>
     *
     * Protobuf type {@code proto.RegionProto.NodeIdSet}
     */
    public  static final class NodeIdSet extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:proto.RegionProto.NodeIdSet)
        NodeIdSetOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use NodeIdSet.newBuilder() to construct.
      private NodeIdSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private NodeIdSet() {
        nodeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private NodeIdSet(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  nodeId_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                nodeId_.add(s);
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            nodeId_ = nodeId_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_NodeIdSet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_NodeIdSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.class, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder.class);
      }

      public static final int NODE_ID_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList nodeId_;
      /**
       * <code>repeated string node_id = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNodeIdList() {
        return nodeId_;
      }
      /**
       * <code>repeated string node_id = 1;</code>
       */
      public int getNodeIdCount() {
        return nodeId_.size();
      }
      /**
       * <code>repeated string node_id = 1;</code>
       */
      public java.lang.String getNodeId(int index) {
        return nodeId_.get(index);
      }
      /**
       * <code>repeated string node_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes(int index) {
        return nodeId_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < nodeId_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < nodeId_.size(); i++) {
            dataSize += computeStringSizeNoTag(nodeId_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getNodeIdList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet)) {
          return super.equals(obj);
        }
        org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet other = (org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet) obj;

        boolean result = true;
        result = result && getNodeIdList()
            .equals(other.getNodeIdList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getNodeIdCount() > 0) {
          hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
          hash = (53 * hash) + getNodeIdList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * List&lt;Set&lt;NodeId&gt;&gt; masters();
       * Since masters is a list of set of NodeIds,
       * the following message is required.
       * </pre>
       *
       * Protobuf type {@code proto.RegionProto.NodeIdSet}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.RegionProto.NodeIdSet)
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_NodeIdSet_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_NodeIdSet_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.class, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder.class);
        }

        // Construct using org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          nodeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_NodeIdSet_descriptor;
        }

        @java.lang.Override
        public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getDefaultInstanceForType() {
          return org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.getDefaultInstance();
        }

        @java.lang.Override
        public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet build() {
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet buildPartial() {
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet result = new org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeId_ = nodeId_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeId_ = nodeId_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet) {
            return mergeFrom((org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet other) {
          if (other == org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.getDefaultInstance()) return this;
          if (!other.nodeId_.isEmpty()) {
            if (nodeId_.isEmpty()) {
              nodeId_ = other.nodeId_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeIdIsMutable();
              nodeId_.addAll(other.nodeId_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList nodeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureNodeIdIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeId_ = new com.google.protobuf.LazyStringArrayList(nodeId_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getNodeIdList() {
          return nodeId_.getUnmodifiableView();
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public int getNodeIdCount() {
          return nodeId_.size();
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public java.lang.String getNodeId(int index) {
          return nodeId_.get(index);
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNodeIdBytes(int index) {
          return nodeId_.getByteString(index);
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public Builder setNodeId(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIdIsMutable();
          nodeId_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public Builder addNodeId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIdIsMutable();
          nodeId_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public Builder addAllNodeId(
            java.lang.Iterable<java.lang.String> values) {
          ensureNodeIdIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeId_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public Builder clearNodeId() {
          nodeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string node_id = 1;</code>
         */
        public Builder addNodeIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureNodeIdIsMutable();
          nodeId_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.RegionProto.NodeIdSet)
      }

      // @@protoc_insertion_point(class_scope:proto.RegionProto.NodeIdSet)
      private static final org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet();
      }

      public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<NodeIdSet>
          PARSER = new com.google.protobuf.AbstractParser<NodeIdSet>() {
        @java.lang.Override
        public NodeIdSet parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NodeIdSet(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<NodeIdSet> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<NodeIdSet> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int REGION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object regionId_;
    /**
     * <code>string region_id = 1;</code>
     */
    public java.lang.String getRegionId() {
      java.lang.Object ref = regionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regionId_ = s;
        return s;
      }
    }
    /**
     * <code>string region_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRegionIdBytes() {
      java.lang.Object ref = regionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.proto.RegionTypeProto type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.RegionTypeProto type = 2;</code>
     */
    public org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto getType() {
      @SuppressWarnings("deprecation")
      org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto result = org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.valueOf(type_);
      return result == null ? org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASTERS_FIELD_NUMBER = 4;
    private java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> masters_;
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    public java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> getMastersList() {
      return masters_;
    }
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    public java.util.List<? extends org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder> 
        getMastersOrBuilderList() {
      return masters_;
    }
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    public int getMastersCount() {
      return masters_.size();
    }
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getMasters(int index) {
      return masters_.get(index);
    }
    /**
     * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
     */
    public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder getMastersOrBuilder(
        int index) {
      return masters_.get(index);
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 5;
    private static final class AnnotationsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_AnnotationsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> annotations_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAnnotations() {
      if (annotations_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AnnotationsDefaultEntryHolder.defaultEntry);
      }
      return annotations_;
    }

    public int getAnnotationsCount() {
      return internalGetAnnotations().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public boolean containsAnnotations(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAnnotations().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
      return getAnnotationsMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
      return internalGetAnnotations().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public java.lang.String getAnnotationsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRegionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, regionId_);
      }
      if (type_ != org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.CONTINENT.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      for (int i = 0; i < masters_.size(); i++) {
        output.writeMessage(4, masters_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAnnotations(),
          AnnotationsDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRegionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, regionId_);
      }
      if (type_ != org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.CONTINENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      for (int i = 0; i < masters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, masters_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAnnotations().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        annotations__ = AnnotationsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, annotations__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto)) {
        return super.equals(obj);
      }
      org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto other = (org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto) obj;

      boolean result = true;
      result = result && getRegionId()
          .equals(other.getRegionId());
      result = result && type_ == other.type_;
      result = result && getName()
          .equals(other.getName());
      result = result && getMastersList()
          .equals(other.getMastersList());
      result = result && internalGetAnnotations().equals(
          other.internalGetAnnotations());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REGION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRegionId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getMastersCount() > 0) {
        hash = (37 * hash) + MASTERS_FIELD_NUMBER;
        hash = (53 * hash) + getMastersList().hashCode();
      }
      if (!internalGetAnnotations().getMap().isEmpty()) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAnnotations().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RegionProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RegionProto)
        org.onosproject.grpc.models.RegionProtoOuterClass.RegionProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.class, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.Builder.class);
      }

      // Construct using org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMastersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        regionId_ = "";

        type_ = 0;

        name_ = "";

        if (mastersBuilder_ == null) {
          masters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          mastersBuilder_.clear();
        }
        internalGetMutableAnnotations().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.internal_static_proto_RegionProto_descriptor;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto getDefaultInstanceForType() {
        return org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto build() {
        org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto buildPartial() {
        org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto result = new org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.regionId_ = regionId_;
        result.type_ = type_;
        result.name_ = name_;
        if (mastersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            masters_ = java.util.Collections.unmodifiableList(masters_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.masters_ = masters_;
        } else {
          result.masters_ = mastersBuilder_.build();
        }
        result.annotations_ = internalGetAnnotations();
        result.annotations_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto) {
          return mergeFrom((org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto other) {
        if (other == org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.getDefaultInstance()) return this;
        if (!other.getRegionId().isEmpty()) {
          regionId_ = other.regionId_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (mastersBuilder_ == null) {
          if (!other.masters_.isEmpty()) {
            if (masters_.isEmpty()) {
              masters_ = other.masters_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMastersIsMutable();
              masters_.addAll(other.masters_);
            }
            onChanged();
          }
        } else {
          if (!other.masters_.isEmpty()) {
            if (mastersBuilder_.isEmpty()) {
              mastersBuilder_.dispose();
              mastersBuilder_ = null;
              masters_ = other.masters_;
              bitField0_ = (bitField0_ & ~0x00000008);
              mastersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMastersFieldBuilder() : null;
            } else {
              mastersBuilder_.addAllMessages(other.masters_);
            }
          }
        }
        internalGetMutableAnnotations().mergeFrom(
            other.internalGetAnnotations());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object regionId_ = "";
      /**
       * <code>string region_id = 1;</code>
       */
      public java.lang.String getRegionId() {
        java.lang.Object ref = regionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          regionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string region_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRegionIdBytes() {
        java.lang.Object ref = regionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string region_id = 1;</code>
       */
      public Builder setRegionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        regionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string region_id = 1;</code>
       */
      public Builder clearRegionId() {
        
        regionId_ = getDefaultInstance().getRegionId();
        onChanged();
        return this;
      }
      /**
       * <code>string region_id = 1;</code>
       */
      public Builder setRegionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        regionId_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.proto.RegionTypeProto type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.proto.RegionTypeProto type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RegionTypeProto type = 2;</code>
       */
      public org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto getType() {
        @SuppressWarnings("deprecation")
        org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto result = org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.valueOf(type_);
        return result == null ? org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.RegionTypeProto type = 2;</code>
       */
      public Builder setType(org.onosproject.grpc.models.RegionEnumsProto.RegionTypeProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RegionTypeProto type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> masters_ =
        java.util.Collections.emptyList();
      private void ensureMastersIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          masters_ = new java.util.ArrayList<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet>(masters_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder> mastersBuilder_;

      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> getMastersList() {
        if (mastersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(masters_);
        } else {
          return mastersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public int getMastersCount() {
        if (mastersBuilder_ == null) {
          return masters_.size();
        } else {
          return mastersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet getMasters(int index) {
        if (mastersBuilder_ == null) {
          return masters_.get(index);
        } else {
          return mastersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder setMasters(
          int index, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet value) {
        if (mastersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMastersIsMutable();
          masters_.set(index, value);
          onChanged();
        } else {
          mastersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder setMasters(
          int index, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder builderForValue) {
        if (mastersBuilder_ == null) {
          ensureMastersIsMutable();
          masters_.set(index, builderForValue.build());
          onChanged();
        } else {
          mastersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder addMasters(org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet value) {
        if (mastersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMastersIsMutable();
          masters_.add(value);
          onChanged();
        } else {
          mastersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder addMasters(
          int index, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet value) {
        if (mastersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMastersIsMutable();
          masters_.add(index, value);
          onChanged();
        } else {
          mastersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder addMasters(
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder builderForValue) {
        if (mastersBuilder_ == null) {
          ensureMastersIsMutable();
          masters_.add(builderForValue.build());
          onChanged();
        } else {
          mastersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder addMasters(
          int index, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder builderForValue) {
        if (mastersBuilder_ == null) {
          ensureMastersIsMutable();
          masters_.add(index, builderForValue.build());
          onChanged();
        } else {
          mastersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder addAllMasters(
          java.lang.Iterable<? extends org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet> values) {
        if (mastersBuilder_ == null) {
          ensureMastersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, masters_);
          onChanged();
        } else {
          mastersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder clearMasters() {
        if (mastersBuilder_ == null) {
          masters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          mastersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public Builder removeMasters(int index) {
        if (mastersBuilder_ == null) {
          ensureMastersIsMutable();
          masters_.remove(index);
          onChanged();
        } else {
          mastersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder getMastersBuilder(
          int index) {
        return getMastersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder getMastersOrBuilder(
          int index) {
        if (mastersBuilder_ == null) {
          return masters_.get(index);  } else {
          return mastersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public java.util.List<? extends org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder> 
           getMastersOrBuilderList() {
        if (mastersBuilder_ != null) {
          return mastersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(masters_);
        }
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder addMastersBuilder() {
        return getMastersFieldBuilder().addBuilder(
            org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder addMastersBuilder(
          int index) {
        return getMastersFieldBuilder().addBuilder(
            index, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RegionProto.NodeIdSet masters = 4;</code>
       */
      public java.util.List<org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder> 
           getMastersBuilderList() {
        return getMastersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder> 
          getMastersFieldBuilder() {
        if (mastersBuilder_ == null) {
          mastersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSet.Builder, org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto.NodeIdSetOrBuilder>(
                  masters_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          masters_ = null;
        }
        return mastersBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> annotations_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAnnotations() {
        if (annotations_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        return annotations_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAnnotations() {
        onChanged();;
        if (annotations_ == null) {
          annotations_ = com.google.protobuf.MapField.newMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        if (!annotations_.isMutable()) {
          annotations_ = annotations_.copy();
        }
        return annotations_;
      }

      public int getAnnotationsCount() {
        return internalGetAnnotations().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public boolean containsAnnotations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAnnotations().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAnnotationsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
        return getAnnotationsMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
        return internalGetAnnotations().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public java.lang.String getAnnotationsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public java.lang.String getAnnotationsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAnnotations() {
        internalGetMutableAnnotations().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public Builder removeAnnotations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAnnotations() {
        return internalGetMutableAnnotations().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */
      public Builder putAnnotations(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public Builder putAllAnnotations(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAnnotations().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.RegionProto)
    }

    // @@protoc_insertion_point(class_scope:proto.RegionProto)
    private static final org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto();
    }

    public static org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegionProto>
        PARSER = new com.google.protobuf.AbstractParser<RegionProto>() {
      @java.lang.Override
      public RegionProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegionProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegionProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegionProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.RegionProtoOuterClass.RegionProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RegionProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RegionProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RegionProto_NodeIdSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RegionProto_NodeIdSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RegionProto_AnnotationsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RegionProto_AnnotationsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021RegionProto.proto\022\005proto\032\026RegionEnumsP" +
      "roto.proto\"\217\002\n\013RegionProto\022\021\n\tregion_id\030" +
      "\001 \001(\t\022$\n\004type\030\002 \001(\0162\026.proto.RegionTypePr" +
      "oto\022\014\n\004name\030\003 \001(\t\022-\n\007masters\030\004 \003(\0132\034.pro" +
      "to.RegionProto.NodeIdSet\0228\n\013annotations\030" +
      "\005 \003(\0132#.proto.RegionProto.AnnotationsEnt" +
      "ry\032\034\n\tNodeIdSet\022\017\n\007node_id\030\001 \003(\t\0322\n\020Anno" +
      "tationsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B\035\n\033org.onosproject.grpc.modelsb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.onosproject.grpc.models.RegionEnumsProto.getDescriptor(),
        }, assigner);
    internal_static_proto_RegionProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RegionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RegionProto_descriptor,
        new java.lang.String[] { "RegionId", "Type", "Name", "Masters", "Annotations", });
    internal_static_proto_RegionProto_NodeIdSet_descriptor =
      internal_static_proto_RegionProto_descriptor.getNestedTypes().get(0);
    internal_static_proto_RegionProto_NodeIdSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RegionProto_NodeIdSet_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_proto_RegionProto_AnnotationsEntry_descriptor =
      internal_static_proto_RegionProto_descriptor.getNestedTypes().get(1);
    internal_static_proto_RegionProto_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RegionProto_AnnotationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.onosproject.grpc.models.RegionEnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
