// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceProto.proto

package org.onosproject.grpc.models;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ServiceProto.proto\022\005proto\032\031OutboundPac" +
      "ketProto.proto\032\023FlowRuleProto.proto\032\030Top" +
      "ologyGraphProto.proto\032\023TopologyProto.pro" +
      "to\032\034EventNotificationProto.proto\032\021Status" +
      "Proto.proto\032\032ControlMessagesProto.proto\032" +
      "\017HostProto.proto\032\021HostIdProto.proto\032\017Por" +
      "tProto.proto\032\023DeviceIdProto.proto\032\021Devic" +
      "eProto.proto\032\027ConnectPointProto.proto\032\030E" +
      "ventListenerProto.proto2N\n\020PacketOutServ" +
      "ice\022:\n\004emit\022\032.proto.OutboundPacketProto\032" +
      "\026.proto.PacketOutStatus2\302\001\n\013FlowService\022" +
      "<\n\016applyFlowRules\022\020.proto.FlowRules\032\030.pr" +
      "oto.FlowServiceStatus\022=\n\017removeFlowRules" +
      "\022\020.proto.FlowRules\032\030.proto.FlowServiceSt" +
      "atus\0226\n\020getFlowRuleCount\022\014.proto.Empty\032\024" +
      ".proto.FlowRuleCount2\252\001\n\013TopoService\0223\n\010" +
      "getGraph\022\014.proto.Empty\032\031.proto.TopologyG" +
      "raphProto\0225\n\017currentTopology\022\014.proto.Emp" +
      "ty\032\024.proto.TopologyProto\022/\n\010getPaths\022\025.p" +
      "roto.getPathRequest\032\014.proto.Paths2\253\002\n\013Ho" +
      "stService\022&\n\010getHosts\022\014.proto.Empty\032\014.pr" +
      "oto.Hosts\0223\n\014getHostCount\022\014.proto.Empty\032" +
      "\025.proto.HostCountProto\022/\n\007getHost\022\022.prot" +
      "o.HostIdProto\032\020.proto.HostProto\022A\n\033getCo" +
      "nnectedHostsByDeviceId\022\024.proto.DeviceIdP" +
      "roto\032\014.proto.Hosts\022K\n!getConnectedHostsB" +
      "yConnectedPoint\022\030.proto.ConnectPointProt" +
      "o\032\014.proto.Hosts2\333\001\n\rDeviceService\0227\n\016get" +
      "DeviceCount\022\014.proto.Empty\032\027.proto.Device" +
      "CountProto\022*\n\ngetDevices\022\014.proto.Empty\032\016" +
      ".proto.Devices\022.\n\010getPorts\022\024.proto.Devic" +
      "eIdProto\032\014.proto.Ports\0225\n\tgetDevice\022\024.pr" +
      "oto.DeviceIdProto\032\022.proto.DeviceProto2\r\n" +
      "\013CoreService2\210\001\n\021EventNotification\022C\n\010re" +
      "gister\022\032.proto.RegistrationRequest\032\033.pro" +
      "to.RegistrationResponse\022.\n\007onEvent\022\014.pro" +
      "to.Topic\032\023.proto.Notification0\0012\261\001\n\rEven" +
      "tListener\0221\n\010regEvent\022\021.proto.RegRequest" +
      "\032\022.proto.RegResponse\022,\n\010onEvents\022\r.proto" +
      ".TopicE\032\017.proto.Listener0\001\022?\n\temitEvent\022" +
      "\032.proto.OutboundPacketProto\032\026.proto.Pack" +
      "etOutStatusB\035\n\033org.onosproject.grpc.mode" +
      "lsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.onosproject.grpc.models.OutboundPacketProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.FlowRuleProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.TopologyGraphProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.TopologyProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.EventNotificationProto.getDescriptor(),
          org.onosproject.grpc.models.StatusProto.getDescriptor(),
          org.onosproject.grpc.models.ControlMessagesProto.getDescriptor(),
          org.onosproject.grpc.models.HostProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.HostIdProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.PortProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.DeviceIdProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.DeviceProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.ConnectPointProtoOuterClass.getDescriptor(),
          org.onosproject.grpc.models.EventListenerProto.getDescriptor(),
        }, assigner);
    org.onosproject.grpc.models.OutboundPacketProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.FlowRuleProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.TopologyGraphProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.TopologyProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.EventNotificationProto.getDescriptor();
    org.onosproject.grpc.models.StatusProto.getDescriptor();
    org.onosproject.grpc.models.ControlMessagesProto.getDescriptor();
    org.onosproject.grpc.models.HostProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.HostIdProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.PortProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.DeviceIdProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.DeviceProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.ConnectPointProtoOuterClass.getDescriptor();
    org.onosproject.grpc.models.EventListenerProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
