// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VersionProto.proto

package org.onosproject.grpc.models;

public final class VersionProtoOuterClass {
  private VersionProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VersionProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.VersionProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 major = 1;</code>
     */
    int getMajor();

    /**
     * <code>int32 minor = 2;</code>
     */
    int getMinor();

    /**
     * <code>string patch = 3;</code>
     */
    java.lang.String getPatch();
    /**
     * <code>string patch = 3;</code>
     */
    com.google.protobuf.ByteString
        getPatchBytes();

    /**
     * <code>string build = 4;</code>
     */
    java.lang.String getBuild();
    /**
     * <code>string build = 4;</code>
     */
    com.google.protobuf.ByteString
        getBuildBytes();
  }
  /**
   * <pre>
   * Corresponds to org.onosproject.core.
   * </pre>
   *
   * Protobuf type {@code proto.VersionProto}
   */
  public  static final class VersionProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.VersionProto)
      VersionProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VersionProto.newBuilder() to construct.
    private VersionProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VersionProto() {
      major_ = 0;
      minor_ = 0;
      patch_ = "";
      build_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VersionProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              major_ = input.readInt32();
              break;
            }
            case 16: {

              minor_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              patch_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              build_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onosproject.grpc.models.VersionProtoOuterClass.internal_static_proto_VersionProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onosproject.grpc.models.VersionProtoOuterClass.internal_static_proto_VersionProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.class, org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.Builder.class);
    }

    public static final int MAJOR_FIELD_NUMBER = 1;
    private int major_;
    /**
     * <code>int32 major = 1;</code>
     */
    public int getMajor() {
      return major_;
    }

    public static final int MINOR_FIELD_NUMBER = 2;
    private int minor_;
    /**
     * <code>int32 minor = 2;</code>
     */
    public int getMinor() {
      return minor_;
    }

    public static final int PATCH_FIELD_NUMBER = 3;
    private volatile java.lang.Object patch_;
    /**
     * <code>string patch = 3;</code>
     */
    public java.lang.String getPatch() {
      java.lang.Object ref = patch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patch_ = s;
        return s;
      }
    }
    /**
     * <code>string patch = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPatchBytes() {
      java.lang.Object ref = patch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILD_FIELD_NUMBER = 4;
    private volatile java.lang.Object build_;
    /**
     * <code>string build = 4;</code>
     */
    public java.lang.String getBuild() {
      java.lang.Object ref = build_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        build_ = s;
        return s;
      }
    }
    /**
     * <code>string build = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBuildBytes() {
      java.lang.Object ref = build_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        build_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (major_ != 0) {
        output.writeInt32(1, major_);
      }
      if (minor_ != 0) {
        output.writeInt32(2, minor_);
      }
      if (!getPatchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, patch_);
      }
      if (!getBuildBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, build_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (major_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, major_);
      }
      if (minor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minor_);
      }
      if (!getPatchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, patch_);
      }
      if (!getBuildBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, build_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto)) {
        return super.equals(obj);
      }
      org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto other = (org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto) obj;

      boolean result = true;
      result = result && (getMajor()
          == other.getMajor());
      result = result && (getMinor()
          == other.getMinor());
      result = result && getPatch()
          .equals(other.getPatch());
      result = result && getBuild()
          .equals(other.getBuild());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAJOR_FIELD_NUMBER;
      hash = (53 * hash) + getMajor();
      hash = (37 * hash) + MINOR_FIELD_NUMBER;
      hash = (53 * hash) + getMinor();
      hash = (37 * hash) + PATCH_FIELD_NUMBER;
      hash = (53 * hash) + getPatch().hashCode();
      hash = (37 * hash) + BUILD_FIELD_NUMBER;
      hash = (53 * hash) + getBuild().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Corresponds to org.onosproject.core.
     * </pre>
     *
     * Protobuf type {@code proto.VersionProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.VersionProto)
        org.onosproject.grpc.models.VersionProtoOuterClass.VersionProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onosproject.grpc.models.VersionProtoOuterClass.internal_static_proto_VersionProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onosproject.grpc.models.VersionProtoOuterClass.internal_static_proto_VersionProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.class, org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.Builder.class);
      }

      // Construct using org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        major_ = 0;

        minor_ = 0;

        patch_ = "";

        build_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onosproject.grpc.models.VersionProtoOuterClass.internal_static_proto_VersionProto_descriptor;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto getDefaultInstanceForType() {
        return org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto build() {
        org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto buildPartial() {
        org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto result = new org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto(this);
        result.major_ = major_;
        result.minor_ = minor_;
        result.patch_ = patch_;
        result.build_ = build_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto) {
          return mergeFrom((org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto other) {
        if (other == org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto.getDefaultInstance()) return this;
        if (other.getMajor() != 0) {
          setMajor(other.getMajor());
        }
        if (other.getMinor() != 0) {
          setMinor(other.getMinor());
        }
        if (!other.getPatch().isEmpty()) {
          patch_ = other.patch_;
          onChanged();
        }
        if (!other.getBuild().isEmpty()) {
          build_ = other.build_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int major_ ;
      /**
       * <code>int32 major = 1;</code>
       */
      public int getMajor() {
        return major_;
      }
      /**
       * <code>int32 major = 1;</code>
       */
      public Builder setMajor(int value) {
        
        major_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 major = 1;</code>
       */
      public Builder clearMajor() {
        
        major_ = 0;
        onChanged();
        return this;
      }

      private int minor_ ;
      /**
       * <code>int32 minor = 2;</code>
       */
      public int getMinor() {
        return minor_;
      }
      /**
       * <code>int32 minor = 2;</code>
       */
      public Builder setMinor(int value) {
        
        minor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minor = 2;</code>
       */
      public Builder clearMinor() {
        
        minor_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object patch_ = "";
      /**
       * <code>string patch = 3;</code>
       */
      public java.lang.String getPatch() {
        java.lang.Object ref = patch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patch = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPatchBytes() {
        java.lang.Object ref = patch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patch = 3;</code>
       */
      public Builder setPatch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patch = 3;</code>
       */
      public Builder clearPatch() {
        
        patch_ = getDefaultInstance().getPatch();
        onChanged();
        return this;
      }
      /**
       * <code>string patch = 3;</code>
       */
      public Builder setPatchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object build_ = "";
      /**
       * <code>string build = 4;</code>
       */
      public java.lang.String getBuild() {
        java.lang.Object ref = build_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          build_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string build = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBuildBytes() {
        java.lang.Object ref = build_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          build_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string build = 4;</code>
       */
      public Builder setBuild(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        build_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string build = 4;</code>
       */
      public Builder clearBuild() {
        
        build_ = getDefaultInstance().getBuild();
        onChanged();
        return this;
      }
      /**
       * <code>string build = 4;</code>
       */
      public Builder setBuildBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        build_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.VersionProto)
    }

    // @@protoc_insertion_point(class_scope:proto.VersionProto)
    private static final org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto();
    }

    public static org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionProto>
        PARSER = new com.google.protobuf.AbstractParser<VersionProto>() {
      @java.lang.Override
      public VersionProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VersionProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VersionProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onosproject.grpc.models.VersionProtoOuterClass.VersionProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_VersionProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_VersionProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022VersionProto.proto\022\005proto\"J\n\014VersionPr" +
      "oto\022\r\n\005major\030\001 \001(\005\022\r\n\005minor\030\002 \001(\005\022\r\n\005pat" +
      "ch\030\003 \001(\t\022\r\n\005build\030\004 \001(\tB\035\n\033org.onosproje" +
      "ct.grpc.modelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_VersionProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_VersionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_VersionProto_descriptor,
        new java.lang.String[] { "Major", "Minor", "Patch", "Build", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
